[2025-01-05T18:27:57.888+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-05T18:27:57.919+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_NB_Fetch_Google_Finance.NB_Notebook_job manual__2025-01-05T18:27:52.611367+00:00 [queued]>
[2025-01-05T18:27:57.941+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_NB_Fetch_Google_Finance.NB_Notebook_job manual__2025-01-05T18:27:52.611367+00:00 [queued]>
[2025-01-05T18:27:57.942+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-05T18:27:57.961+0000] {taskinstance.py:2889} INFO - Executing <Task(DockerOperator): NB_Notebook_job> on 2025-01-05 18:27:52.611367+00:00
[2025-01-05T18:27:57.999+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=220) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-05T18:27:58.018+0000] {standard_task_runner.py:72} INFO - Started process 223 to run task
[2025-01-05T18:27:58.026+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_NB_Fetch_Google_Finance', 'NB_Notebook_job', 'manual__2025-01-05T18:27:52.611367+00:00', '--job-id', '644', '--raw', '--subdir', 'DAGS_FOLDER/dag_NB_Fetch_Google_Finance.py', '--cfg-path', '/tmp/tmp3fgo4vst']
[2025-01-05T18:27:58.028+0000] {standard_task_runner.py:105} INFO - Job 644: Subtask NB_Notebook_job
[2025-01-05T18:27:58.226+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_NB_Fetch_Google_Finance.NB_Notebook_job manual__2025-01-05T18:27:52.611367+00:00 [running]> on host c0503b833e6f
[2025-01-05T18:27:58.472+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Anoop M' AIRFLOW_CTX_DAG_ID='dag_NB_Fetch_Google_Finance' AIRFLOW_CTX_TASK_ID='NB_Notebook_job' AIRFLOW_CTX_EXECUTION_DATE='2025-01-05T18:27:52.611367+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-05T18:27:52.611367+00:00'
[2025-01-05T18:27:58.483+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-05T18:27:59.182+0000] {docker.py:379} INFO - Starting docker container from image spark-cluster:version-1.0.0
[2025-01-05T18:28:06.416+0000] {docker.py:73} INFO - Input Notebook:  /home/jovyan/Notebooks/NB_Fetch_Google_Finance.ipynb
[2025-01-05T18:28:06.440+0000] {docker.py:73} INFO - Output Notebook: /home/jovyan/Notebooks/output/NB_Fetch_Google_Finance.ipynb
[2025-01-05T18:28:12.297+0000] {docker.py:73} INFO - Executing notebook with kernel: python3
[2025-01-05T18:28:12.325+0000] {docker.py:73} INFO - Executing Cell 1---------------------------------------
[2025-01-05T18:28:43.901+0000] {docker.py:73} INFO - :: loading settings :: url = jar:file:/usr/local/spark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-01-05T18:28:44.129+0000] {docker.py:73} INFO - Ivy Default Cache set to: /home/jovyan/.ivy2/cache
[2025-01-05T18:28:44.130+0000] {docker.py:73} INFO - The jars for the packages stored in: /home/jovyan/.ivy2/jars
[2025-01-05T18:28:44.140+0000] {docker.py:73} INFO - io.delta#delta-spark_2.12 added as a dependency
[2025-01-05T18:28:44.148+0000] {docker.py:73} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-30704dd9-09e3-49f4-900b-01fd0bd3c045;1.0
[2025-01-05T18:28:44.149+0000] {docker.py:73} INFO - 	confs: [default]
[2025-01-05T18:28:55.030+0000] {docker.py:73} INFO - 	found io.delta#delta-spark_2.12;3.1.0 in central
[2025-01-05T18:28:55.060+0000] {docker.py:73} INFO - downloading https://repo1.maven.org/maven2/io/delta/delta-spark_2.12/3.1.0/delta-spark_2.12-3.1.0.jar ...
[2025-01-05T18:33:44.147+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-01-05T18:33:44.182+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-01-05T18:33:44.187+0000] {process_utils.py:132} INFO - Sending 15 to group 223. PIDs of all processes in the group: [223]
[2025-01-05T18:33:44.190+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 223
[2025-01-05T18:33:44.199+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-01-05T18:33:44.209+0000] {docker.py:539} INFO - Stopping docker container
[2025-01-05T18:33:44.923+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-05T18:33:44.959+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=223, status='terminated', exitcode=0, started='18:27:57') (223) terminated with exit code 0
