[2025-01-05T14:03:32.950+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-05T14:03:32.976+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_NB_Fetch_Google_Finance.NB_Notebook_job manual__2025-01-05T14:03:30.064264+00:00 [queued]>
[2025-01-05T14:03:32.984+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_NB_Fetch_Google_Finance.NB_Notebook_job manual__2025-01-05T14:03:30.064264+00:00 [queued]>
[2025-01-05T14:03:32.985+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-05T14:03:32.999+0000] {taskinstance.py:2889} INFO - Executing <Task(DockerOperator): NB_Notebook_job> on 2025-01-05 14:03:30.064264+00:00
[2025-01-05T14:03:33.009+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=332) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-05T14:03:33.012+0000] {standard_task_runner.py:72} INFO - Started process 335 to run task
[2025-01-05T14:03:33.014+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_NB_Fetch_Google_Finance', 'NB_Notebook_job', 'manual__2025-01-05T14:03:30.064264+00:00', '--job-id', '598', '--raw', '--subdir', 'DAGS_FOLDER/dag_NB_Fetch_Google_Finance.py', '--cfg-path', '/tmp/tmpye6dmk_x']
[2025-01-05T14:03:33.016+0000] {standard_task_runner.py:105} INFO - Job 598: Subtask NB_Notebook_job
[2025-01-05T14:03:33.089+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_NB_Fetch_Google_Finance.NB_Notebook_job manual__2025-01-05T14:03:30.064264+00:00 [running]> on host 44275986e897
[2025-01-05T14:03:33.174+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Anoop M' AIRFLOW_CTX_DAG_ID='dag_NB_Fetch_Google_Finance' AIRFLOW_CTX_TASK_ID='NB_Notebook_job' AIRFLOW_CTX_EXECUTION_DATE='2025-01-05T14:03:30.064264+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-05T14:03:30.064264+00:00'
[2025-01-05T14:03:33.175+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-05T14:03:33.384+0000] {docker.py:379} INFO - Starting docker container from image spark-cluster:version-1.0.0
[2025-01-05T14:03:36.491+0000] {docker.py:73} INFO - Input Notebook:  /home/jovyan/Notebooks/NB_Fetch_Google_Finance.ipynb
[2025-01-05T14:03:36.498+0000] {docker.py:73} INFO - Output Notebook: /home/jovyan/Notebooks/output/NB_Fetch_Google_Finance.ipynb
[2025-01-05T14:03:39.827+0000] {docker.py:73} INFO - Executing notebook with kernel: python3
[2025-01-05T14:03:39.838+0000] {docker.py:73} INFO - Executing Cell 1---------------------------------------
[2025-01-05T14:03:47.539+0000] {docker.py:73} INFO - :: loading settings :: url = jar:file:/usr/local/spark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-01-05T14:03:47.864+0000] {docker.py:73} INFO - Ivy Default Cache set to: /home/jovyan/.ivy2/cache
[2025-01-05T14:03:47.872+0000] {docker.py:73} INFO - The jars for the packages stored in: /home/jovyan/.ivy2/jars
[2025-01-05T14:03:47.877+0000] {docker.py:73} INFO - io.delta#delta-spark_2.12 added as a dependency
[2025-01-05T14:03:47.878+0000] {docker.py:73} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-b3ebaf1d-7374-4643-bc9b-b70407e55986;1.0
[2025-01-05T14:03:47.883+0000] {docker.py:73} INFO - 	confs: [default]
[2025-01-05T14:03:50.764+0000] {docker.py:73} INFO - 	found io.delta#delta-spark_2.12;3.1.0 in central
[2025-01-05T14:03:51.260+0000] {docker.py:73} INFO - 	found io.delta#delta-storage;3.1.0 in central
[2025-01-05T14:03:53.482+0000] {docker.py:73} INFO - 	found org.antlr#antlr4-runtime;4.9.3 in central
[2025-01-05T14:03:53.725+0000] {docker.py:73} INFO - downloading https://repo1.maven.org/maven2/io/delta/delta-spark_2.12/3.1.0/delta-spark_2.12-3.1.0.jar ...
[2025-01-05T14:03:55.512+0000] {docker.py:73} INFO - 	[SUCCESSFUL ] io.delta#delta-spark_2.12;3.1.0!delta-spark_2.12.jar (2004ms)
[2025-01-05T14:03:55.739+0000] {docker.py:73} INFO - downloading https://repo1.maven.org/maven2/io/delta/delta-storage/3.1.0/delta-storage-3.1.0.jar ...
[2025-01-05T14:03:55.967+0000] {docker.py:73} INFO - 	[SUCCESSFUL ] io.delta#delta-storage;3.1.0!delta-storage.jar (453ms)
[2025-01-05T14:03:56.194+0000] {docker.py:73} INFO - downloading https://repo1.maven.org/maven2/org/antlr/antlr4-runtime/4.9.3/antlr4-runtime-4.9.3.jar ...
[2025-01-05T14:03:56.432+0000] {docker.py:73} INFO - 	[SUCCESSFUL ] org.antlr#antlr4-runtime;4.9.3!antlr4-runtime.jar (459ms)
[2025-01-05T14:03:56.433+0000] {docker.py:73} INFO - :: resolution report :: resolve 5619ms :: artifacts dl 2933ms
[2025-01-05T14:03:56.435+0000] {docker.py:73} INFO - 	:: modules in use:
[2025-01-05T14:03:56.436+0000] {docker.py:73} INFO - 	io.delta#delta-spark_2.12;3.1.0 from central in [default]
[2025-01-05T14:03:56.438+0000] {docker.py:73} INFO - 	io.delta#delta-storage;3.1.0 from central in [default]
[2025-01-05T14:03:56.439+0000] {docker.py:73} INFO - 	org.antlr#antlr4-runtime;4.9.3 from central in [default]
[2025-01-05T14:03:56.440+0000] {docker.py:73} INFO - 	---------------------------------------------------------------------
[2025-01-05T14:03:56.441+0000] {docker.py:73} INFO - 	|                  |            modules            ||   artifacts   |
[2025-01-05T14:03:56.442+0000] {docker.py:73} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2025-01-05T14:03:56.443+0000] {docker.py:73} INFO - 	---------------------------------------------------------------------
[2025-01-05T14:03:56.443+0000] {docker.py:73} INFO - 	|      default     |   3   |   3   |   3   |   0   ||   3   |   3   |
[2025-01-05T14:03:56.443+0000] {docker.py:73} INFO - 	---------------------------------------------------------------------
[2025-01-05T14:03:56.455+0000] {docker.py:73} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-b3ebaf1d-7374-4643-bc9b-b70407e55986
[2025-01-05T14:03:56.456+0000] {docker.py:73} INFO - 	confs: [default]
[2025-01-05T14:03:56.528+0000] {docker.py:73} INFO - 	3 artifacts copied, 0 already retrieved (5727kB/64ms)
[2025-01-05T14:03:57.076+0000] {docker.py:73} INFO - 25/01/05 14:03:57 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-01-05T14:03:57.641+0000] {docker.py:73} INFO - Setting default log level to "
[2025-01-05T14:03:57.646+0000] {docker.py:73} INFO - WARN".
[2025-01-05T14:03:57.647+0000] {docker.py:73} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2025-01-05T14:03:58.627+0000] {docker.py:73} INFO - 25/01/05 14:03:58 WARN StandaloneSchedulerBackend: Dynamic allocation enabled without spark.executor.cores explicitly set, you may get more executors allocated than expected. It's recommended to set spark.executor.cores explicitly. Please check SPARK-30299 for more details.
[2025-01-05T14:03:59.049+0000] {docker.py:73} INFO - 25/01/05 14:03:59 WARN Utils: spark.executor.instances less than spark.dynamicAllocation.minExecutors is invalid, ignoring its setting, please update your configs.
[2025-01-05T14:04:01.050+0000] {docker.py:73} INFO - <pyspark.sql.session.SparkSession at 0xffff495b8490>
[2025-01-05T14:04:01.057+0000] {docker.py:73} INFO - Ending Cell 1------------------------------------------
[2025-01-05T14:04:01.060+0000] {docker.py:73} INFO - Executing Cell 2---------------------------------------
[2025-01-05T14:04:05.989+0000] {docker.py:73} INFO - [Stage 0:>                                                          (0 + 1) / 1]
[2025-01-05T14:04:07.272+0000] {docker.py:73} INFO - 
[2025-01-05T14:04:07.534+0000] {docker.py:73} INFO - Ending Cell 2------------------------------------------
[2025-01-05T14:04:07.542+0000] {docker.py:73} INFO - Executing Cell 3---------------------------------------
[2025-01-05T14:04:08.528+0000] {docker.py:73} INFO - Ending Cell 3------------------------------------------
[2025-01-05T14:04:11.203+0000] {docker.py:73} INFO - Traceback (most recent call last):
[2025-01-05T14:04:11.215+0000] {docker.py:73} INFO -   File "/opt/conda/bin/papermill", line 8, in <module>
[2025-01-05T14:04:11.215+0000] {docker.py:73} INFO -     sys.exit(papermill())
[2025-01-05T14:04:11.216+0000] {docker.py:73} INFO -              ^^^^^^^^^^^
[2025-01-05T14:04:11.216+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
[2025-01-05T14:04:11.216+0000] {docker.py:73} INFO -     return self.main(*args, **kwargs)
[2025-01-05T14:04:11.216+0000] {docker.py:73} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-01-05T14:04:11.217+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 1078, in main
[2025-01-05T14:04:11.217+0000] {docker.py:73} INFO -     rv = self.invoke(ctx)
[2025-01-05T14:04:11.217+0000] {docker.py:73} INFO -          ^^^^^^^^^^^^^^^^
[2025-01-05T14:04:11.217+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
[2025-01-05T14:04:11.218+0000] {docker.py:73} INFO -     return ctx.invoke(self.callback, **ctx.params)
[2025-01-05T14:04:11.218+0000] {docker.py:73} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-01-05T14:04:11.218+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 783, in invoke
[2025-01-05T14:04:11.218+0000] {docker.py:73} INFO -     return __callback(*args, **kwargs)
[2025-01-05T14:04:11.218+0000] {docker.py:73} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-01-05T14:04:11.218+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
[2025-01-05T14:04:11.218+0000] {docker.py:73} INFO -     return f(get_current_context(), *args, **kwargs)
[2025-01-05T14:04:11.219+0000] {docker.py:73} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-01-05T14:04:11.219+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/papermill/cli.py", line 235, in papermill
[2025-01-05T14:04:11.219+0000] {docker.py:73} INFO -     execute_notebook(
[2025-01-05T14:04:11.219+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/papermill/execute.py", line 131, in execute_notebook
[2025-01-05T14:04:11.219+0000] {docker.py:73} INFO -     raise_for_execution_errors(nb, output_path)
[2025-01-05T14:04:11.220+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/papermill/execute.py", line 251, in raise_for_execution_errors
[2025-01-05T14:04:11.220+0000] {docker.py:73} INFO -     raise error
[2025-01-05T14:04:11.220+0000] {docker.py:73} INFO - papermill.exceptions.PapermillExecutionError: 
[2025-01-05T14:04:11.220+0000] {docker.py:73} INFO - ---------------------------------------------------------------------------
[2025-01-05T14:04:11.220+0000] {docker.py:73} INFO - Exception encountered at "In [3]":
[2025-01-05T14:04:11.221+0000] {docker.py:73} INFO - ---------------------------------------------------------------------------
[2025-01-05T14:04:11.221+0000] {docker.py:73} INFO - AnalysisException                         Traceback (most recent call last)
[2025-01-05T14:04:11.221+0000] {docker.py:73} INFO - Cell In[3], line 1
[2025-01-05T14:04:11.221+0000] {docker.py:73} INFO - ----> 1 trgt_path_processed = dfpath.filter(col("DataFeedName") == "Stock_Delta_Path").select('Path').collect()[0][0]
[2025-01-05T14:04:11.221+0000] {docker.py:73} INFO -       2 trgt_path_csv = dfpath.filter(col("DataFeedName") == "Stock_CSV_Path").select('Path').collect()[0][0]
[2025-01-05T14:04:11.222+0000] {docker.py:73} INFO - 
[2025-01-05T14:04:11.222+0000] {docker.py:73} INFO - File /opt/conda/lib/python3.11/site-packages/pyspark/sql/dataframe.py:3331, in DataFrame.filter(self, condition)
[2025-01-05T14:04:11.222+0000] {docker.py:73} INFO -    3329     jdf = self._jdf.filter(condition)
[2025-01-05T14:04:11.223+0000] {docker.py:73} INFO -    3330 elif isinstance(condition, Column):
[2025-01-05T14:04:11.223+0000] {docker.py:73} INFO - -> 3331     jdf = self._jdf.filter(condition._jc)
[2025-01-05T14:04:11.224+0000] {docker.py:73} INFO -    3332 else:
[2025-01-05T14:04:11.224+0000] {docker.py:73} INFO -    3333     raise PySparkTypeError(
[2025-01-05T14:04:11.225+0000] {docker.py:73} INFO -    3334         error_class="NOT_COLUMN_OR_STR",
[2025-01-05T14:04:11.225+0000] {docker.py:73} INFO -    3335         message_parameters={"arg_name": "condition", "arg_type": type(condition).__name__},
[2025-01-05T14:04:11.226+0000] {docker.py:73} INFO -    3336     )
[2025-01-05T14:04:11.226+0000] {docker.py:73} INFO - 
[2025-01-05T14:04:11.226+0000] {docker.py:73} INFO - File /opt/conda/lib/python3.11/site-packages/py4j/java_gateway.py:1322, in JavaMember.__call__(self, *args)
[2025-01-05T14:04:11.227+0000] {docker.py:73} INFO -    1316 command = proto.CALL_COMMAND_NAME +\
[2025-01-05T14:04:11.227+0000] {docker.py:73} INFO -    1317     self.command_header +\
[2025-01-05T14:04:11.227+0000] {docker.py:73} INFO -    1318     args_command +\
[2025-01-05T14:04:11.228+0000] {docker.py:73} INFO -    1319     proto.END_COMMAND_PART
[2025-01-05T14:04:11.228+0000] {docker.py:73} INFO -    1321 answer = self.gateway_client.send_command(command)
[2025-01-05T14:04:11.228+0000] {docker.py:73} INFO - -> 1322 return_value = get_return_value(
[2025-01-05T14:04:11.228+0000] {docker.py:73} INFO -    1323     answer, self.gateway_client, self.target_id, self.name)
[2025-01-05T14:04:11.228+0000] {docker.py:73} INFO -    1325 for temp_arg in temp_args:
[2025-01-05T14:04:11.228+0000] {docker.py:73} INFO -    1326     if hasattr(temp_arg, "_detach"):
[2025-01-05T14:04:11.229+0000] {docker.py:73} INFO - 
[2025-01-05T14:04:11.229+0000] {docker.py:73} INFO - File /opt/conda/lib/python3.11/site-packages/pyspark/errors/exceptions/captured.py:185, in capture_sql_exception.<locals>.deco(*a, **kw)
[2025-01-05T14:04:11.229+0000] {docker.py:73} INFO -     181 converted = convert_exception(e.java_exception)
[2025-01-05T14:04:11.229+0000] {docker.py:73} INFO -     182 if not isinstance(converted, UnknownException):
[2025-01-05T14:04:11.229+0000] {docker.py:73} INFO -     183     # Hide where the exception came from that shows a non-Pythonic
[2025-01-05T14:04:11.229+0000] {docker.py:73} INFO -     184     # JVM exception message.
[2025-01-05T14:04:11.230+0000] {docker.py:73} INFO - --> 185     raise converted from None
[2025-01-05T14:04:11.230+0000] {docker.py:73} INFO -     186 else:
[2025-01-05T14:04:11.230+0000] {docker.py:73} INFO -     187     raise
[2025-01-05T14:04:11.230+0000] {docker.py:73} INFO - 
[2025-01-05T14:04:11.230+0000] {docker.py:73} INFO - AnalysisException: [UNRESOLVED_COLUMN.WITH_SUGGESTION] A column or function parameter with name `DataFeedName` cannot be resolved. Did you mean one of the following? [`_c0`, `_c1`].;
[2025-01-05T14:04:11.230+0000] {docker.py:73} INFO - 'Filter ('DataFeedName = Stock_Delta_Path)
[2025-01-05T14:04:11.230+0000] {docker.py:73} INFO - +- Relation [_c0#17,_c1#18] csv
[2025-01-05T14:04:11.912+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 519, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 396, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 453, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-01-05T14:04:11.933+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dag_NB_Fetch_Google_Finance, task_id=NB_Notebook_job, run_id=manual__2025-01-05T14:03:30.064264+00:00, execution_date=20250105T140330, start_date=20250105T140332, end_date=20250105T140411
[2025-01-05T14:04:11.995+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-05T14:04:11.996+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 598 for task NB_Notebook_job (Docker container failed: {'StatusCode': 1}; 335)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 519, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 396, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 453, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-01-05T14:04:12.050+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-05T14:04:12.118+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-05T14:04:12.119+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
