[2025-01-05T14:05:33.306+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-05T14:05:33.332+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_NB_Fetch_Google_Finance.NB_Notebook_job manual__2025-01-05T14:05:30.215328+00:00 [queued]>
[2025-01-05T14:05:33.339+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_NB_Fetch_Google_Finance.NB_Notebook_job manual__2025-01-05T14:05:30.215328+00:00 [queued]>
[2025-01-05T14:05:33.339+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-05T14:05:33.355+0000] {taskinstance.py:2889} INFO - Executing <Task(DockerOperator): NB_Notebook_job> on 2025-01-05 14:05:30.215328+00:00
[2025-01-05T14:05:33.366+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=374) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-05T14:05:33.369+0000] {standard_task_runner.py:72} INFO - Started process 377 to run task
[2025-01-05T14:05:33.368+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_NB_Fetch_Google_Finance', 'NB_Notebook_job', 'manual__2025-01-05T14:05:30.215328+00:00', '--job-id', '603', '--raw', '--subdir', 'DAGS_FOLDER/dag_NB_Fetch_Google_Finance.py', '--cfg-path', '/tmp/tmpzaspw4fg']
[2025-01-05T14:05:33.373+0000] {standard_task_runner.py:105} INFO - Job 603: Subtask NB_Notebook_job
[2025-01-05T14:05:33.444+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_NB_Fetch_Google_Finance.NB_Notebook_job manual__2025-01-05T14:05:30.215328+00:00 [running]> on host 44275986e897
[2025-01-05T14:05:33.529+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Anoop M' AIRFLOW_CTX_DAG_ID='dag_NB_Fetch_Google_Finance' AIRFLOW_CTX_TASK_ID='NB_Notebook_job' AIRFLOW_CTX_EXECUTION_DATE='2025-01-05T14:05:30.215328+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-05T14:05:30.215328+00:00'
[2025-01-05T14:05:33.530+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-05T14:05:33.726+0000] {docker.py:379} INFO - Starting docker container from image spark-cluster:version-1.0.0
[2025-01-05T14:05:37.246+0000] {docker.py:73} INFO - Input Notebook:  /home/jovyan/Notebooks/NB_Fetch_Google_Finance.ipynb
[2025-01-05T14:05:37.287+0000] {docker.py:73} INFO - Output Notebook: /home/jovyan/Notebooks/output/NB_Fetch_Google_Finance.ipynb
[2025-01-05T14:05:40.528+0000] {docker.py:73} INFO - Executing notebook with kernel: python3
[2025-01-05T14:05:40.541+0000] {docker.py:73} INFO - Executing Cell 1---------------------------------------
[2025-01-05T14:05:44.749+0000] {docker.py:73} INFO - :: loading settings :: url = jar:file:/usr/local/spark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-01-05T14:05:44.939+0000] {docker.py:73} INFO - Ivy Default Cache set to: /home/jovyan/.ivy2/cache
[2025-01-05T14:05:44.942+0000] {docker.py:73} INFO - The jars for the packages stored in: /home/jovyan/.ivy2/jars
[2025-01-05T14:05:44.957+0000] {docker.py:73} INFO - io.delta#delta-spark_2.12 added as a dependency
[2025-01-05T14:05:44.961+0000] {docker.py:73} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-8963a264-a8d4-4326-a320-d0d543e4e977;1.0
[2025-01-05T14:05:44.963+0000] {docker.py:73} INFO - 	confs: [default]
[2025-01-05T14:06:02.335+0000] {docker.py:73} INFO - :: resolution report :: resolve 17374ms :: artifacts dl 0ms
[2025-01-05T14:06:02.345+0000] {docker.py:73} INFO - 	:: modules in use:
[2025-01-05T14:06:02.345+0000] {docker.py:73} INFO - 	---------------------------------------------------------------------
[2025-01-05T14:06:02.345+0000] {docker.py:73} INFO - 	|                  |            modules            ||   artifacts   |
[2025-01-05T14:06:02.346+0000] {docker.py:73} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2025-01-05T14:06:02.346+0000] {docker.py:73} INFO - 	---------------------------------------------------------------------
[2025-01-05T14:06:02.346+0000] {docker.py:73} INFO - 	|      default     |   1   |   0   |   0   |   0   ||   0   |   0   |
[2025-01-05T14:06:02.347+0000] {docker.py:73} INFO - 	---------------------------------------------------------------------
[2025-01-05T14:06:02.347+0000] {docker.py:73} INFO - 
[2025-01-05T14:06:02.347+0000] {docker.py:73} INFO - :: problems summary ::
[2025-01-05T14:06:02.348+0000] {docker.py:73} INFO - :::: WARNINGS
[2025-01-05T14:06:02.348+0000] {docker.py:73} INFO - 		module not found: io.delta#delta-spark_2.12;3.1.0
[2025-01-05T14:06:02.348+0000] {docker.py:73} INFO - 
[2025-01-05T14:06:02.349+0000] {docker.py:73} INFO - 	==== local-m2-cache: tried
[2025-01-05T14:06:02.349+0000] {docker.py:73} INFO - 
[2025-01-05T14:06:02.349+0000] {docker.py:73} INFO - 	  file:/home/jovyan/.m2/repository/io/delta/delta-spark_2.12/3.1.0/delta-spark_2.12-3.1.0.pom
[2025-01-05T14:06:02.349+0000] {docker.py:73} INFO - 
[2025-01-05T14:06:02.349+0000] {docker.py:73} INFO - 	  -- artifact io.delta#delta-spark_2.12;3.1.0!delta-spark_2.12.jar:
[2025-01-05T14:06:02.350+0000] {docker.py:73} INFO - 
[2025-01-05T14:06:02.350+0000] {docker.py:73} INFO - 	  file:/home/jovyan/.m2/repository/io/delta/delta-spark_2.12/3.1.0/delta-spark_2.12-3.1.0.jar
[2025-01-05T14:06:02.350+0000] {docker.py:73} INFO - 
[2025-01-05T14:06:02.350+0000] {docker.py:73} INFO - 	==== local-ivy-cache: tried
[2025-01-05T14:06:02.350+0000] {docker.py:73} INFO - 
[2025-01-05T14:06:02.350+0000] {docker.py:73} INFO - 	  /home/jovyan/.ivy2/local/io.delta/delta-spark_2.12/3.1.0/ivys/ivy.xml
[2025-01-05T14:06:02.351+0000] {docker.py:73} INFO - 
[2025-01-05T14:06:02.351+0000] {docker.py:73} INFO - 	  -- artifact io.delta#delta-spark_2.12;3.1.0!delta-spark_2.12.jar:
[2025-01-05T14:06:02.351+0000] {docker.py:73} INFO - 
[2025-01-05T14:06:02.351+0000] {docker.py:73} INFO - 	  /home/jovyan/.ivy2/local/io.delta/delta-spark_2.12/3.1.0/jars/delta-spark_2.12.jar
[2025-01-05T14:06:02.351+0000] {docker.py:73} INFO - 
[2025-01-05T14:06:02.351+0000] {docker.py:73} INFO - 	==== central: tried
[2025-01-05T14:06:02.352+0000] {docker.py:73} INFO - 
[2025-01-05T14:06:02.352+0000] {docker.py:73} INFO - 	  https://repo1.maven.org/maven2/io/delta/delta-spark_2.12/3.1.0/delta-spark_2.12-3.1.0.pom
[2025-01-05T14:06:02.352+0000] {docker.py:73} INFO - 
[2025-01-05T14:06:02.352+0000] {docker.py:73} INFO - 	  -- artifact io.delta#delta-spark_2.12;3.1.0!delta-spark_2.12.jar:
[2025-01-05T14:06:02.352+0000] {docker.py:73} INFO - 
[2025-01-05T14:06:02.352+0000] {docker.py:73} INFO - 	  https://repo1.maven.org/maven2/io/delta/delta-spark_2.12/3.1.0/delta-spark_2.12-3.1.0.jar
[2025-01-05T14:06:02.353+0000] {docker.py:73} INFO - 
[2025-01-05T14:06:02.353+0000] {docker.py:73} INFO - 	==== spark-packages: tried
[2025-01-05T14:06:02.353+0000] {docker.py:73} INFO - 
[2025-01-05T14:06:02.353+0000] {docker.py:73} INFO - 	  https://repos.spark-packages.org/io/delta/delta-spark_2.12/3.1.0/delta-spark_2.12-3.1.0.pom
[2025-01-05T14:06:02.353+0000] {docker.py:73} INFO - 
[2025-01-05T14:06:02.353+0000] {docker.py:73} INFO - 	  -- artifact io.delta#delta-spark_2.12;3.1.0!delta-spark_2.12.jar:
[2025-01-05T14:06:02.353+0000] {docker.py:73} INFO - 
[2025-01-05T14:06:02.354+0000] {docker.py:73} INFO - 	  https://repos.spark-packages.org/io/delta/delta-spark_2.12/3.1.0/delta-spark_2.12-3.1.0.jar
[2025-01-05T14:06:02.354+0000] {docker.py:73} INFO - 
[2025-01-05T14:06:02.354+0000] {docker.py:73} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2025-01-05T14:06:02.354+0000] {docker.py:73} INFO - 
[2025-01-05T14:06:02.354+0000] {docker.py:73} INFO - 		::          UNRESOLVED DEPENDENCIES         ::
[2025-01-05T14:06:02.354+0000] {docker.py:73} INFO - 
[2025-01-05T14:06:02.354+0000] {docker.py:73} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2025-01-05T14:06:02.354+0000] {docker.py:73} INFO - 
[2025-01-05T14:06:02.355+0000] {docker.py:73} INFO - 		:: io.delta#delta-spark_2.12;3.1.0: not found
[2025-01-05T14:06:02.355+0000] {docker.py:73} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2025-01-05T14:06:02.355+0000] {docker.py:73} INFO - 
[2025-01-05T14:06:02.355+0000] {docker.py:73} INFO - 
[2025-01-05T14:06:02.356+0000] {docker.py:73} INFO - :::: ERRORS
[2025-01-05T14:06:02.356+0000] {docker.py:73} INFO - 	Server access error at url https://repo1.maven.org/maven2/io/delta/delta-spark_2.12/3.1.0/delta-spark_2.12-3.1.0.pom (java.net.ConnectException: Connection refused)
[2025-01-05T14:06:02.356+0000] {docker.py:73} INFO - 
[2025-01-05T14:06:02.356+0000] {docker.py:73} INFO - 	Server access error at url https://repo1.maven.org/maven2/io/delta/delta-spark_2.12/3.1.0/delta-spark_2.12-3.1.0.jar (java.net.ConnectException: Connection refused)
[2025-01-05T14:06:02.356+0000] {docker.py:73} INFO - 
[2025-01-05T14:06:02.356+0000] {docker.py:73} INFO - 
[2025-01-05T14:06:02.356+0000] {docker.py:73} INFO - :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
[2025-01-05T14:06:02.356+0000] {docker.py:73} INFO - Exception in thread "main"
[2025-01-05T14:06:02.357+0000] {docker.py:73} INFO - java.lang.RuntimeException: [unresolved dependency: io.delta#delta-spark_2.12;3.1.0: not found]
[2025-01-05T14:06:02.357+0000] {docker.py:73} INFO - 	at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1537)
[2025-01-05T14:06:02.357+0000] {docker.py:73} INFO - 	at org.apache.spark.util.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:185)
[2025-01-05T14:06:02.357+0000] {docker.py:73} INFO - 	at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:334)
[2025-01-05T14:06:02.357+0000] {docker.py:73} INFO - 	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:964)
[2025-01-05T14:06:02.358+0000] {docker.py:73} INFO - 	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:194)
[2025-01-05T14:06:02.358+0000] {docker.py:73} INFO - 	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:217)
[2025-01-05T14:06:02.358+0000] {docker.py:73} INFO - 	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:91)
[2025-01-05T14:06:02.358+0000] {docker.py:73} INFO - 	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1120)
[2025-01-05T14:06:02.358+0000] {docker.py:73} INFO - 	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1129)
[2025-01-05T14:06:02.358+0000] {docker.py:73} INFO - 	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2025-01-05T14:06:03.064+0000] {docker.py:73} INFO - Ending Cell 1------------------------------------------
[2025-01-05T14:06:03.618+0000] {docker.py:73} INFO - Traceback (most recent call last):
[2025-01-05T14:06:03.623+0000] {docker.py:73} INFO -   File "/opt/conda/bin/papermill", line 8, in <module>
[2025-01-05T14:06:03.625+0000] {docker.py:73} INFO -     sys.exit(papermill())
[2025-01-05T14:06:03.628+0000] {docker.py:73} INFO -              ^^^^^^^^^^^
[2025-01-05T14:06:03.652+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
[2025-01-05T14:06:03.653+0000] {docker.py:73} INFO -     return self.main(*args, **kwargs)
[2025-01-05T14:06:03.653+0000] {docker.py:73} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-01-05T14:06:03.656+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 1078, in main
[2025-01-05T14:06:03.662+0000] {docker.py:73} INFO -     rv = self.invoke(ctx)
[2025-01-05T14:06:03.663+0000] {docker.py:73} INFO -          ^^^^^^^^^^^^^^^^
[2025-01-05T14:06:03.663+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
[2025-01-05T14:06:03.664+0000] {docker.py:73} INFO -     return ctx.invoke(self.callback, **ctx.params)
[2025-01-05T14:06:03.665+0000] {docker.py:73} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-01-05T14:06:03.665+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 783, in invoke
[2025-01-05T14:06:03.666+0000] {docker.py:73} INFO -     return __callback(*args, **kwargs)
[2025-01-05T14:06:03.667+0000] {docker.py:73} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-01-05T14:06:03.667+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
[2025-01-05T14:06:03.668+0000] {docker.py:73} INFO -     return f(get_current_context(), *args, **kwargs)
[2025-01-05T14:06:03.669+0000] {docker.py:73} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-01-05T14:06:03.669+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/papermill/cli.py", line 235, in papermill
[2025-01-05T14:06:03.670+0000] {docker.py:73} INFO -     execute_notebook(
[2025-01-05T14:06:03.671+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/papermill/execute.py", line 131, in execute_notebook
[2025-01-05T14:06:03.672+0000] {docker.py:73} INFO -     raise_for_execution_errors(nb, output_path)
[2025-01-05T14:06:03.673+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/papermill/execute.py", line 251, in raise_for_execution_errors
[2025-01-05T14:06:03.674+0000] {docker.py:73} INFO -     raise error
[2025-01-05T14:06:03.675+0000] {docker.py:73} INFO - papermill.exceptions.PapermillExecutionError: 
[2025-01-05T14:06:03.676+0000] {docker.py:73} INFO - ---------------------------------------------------------------------------
[2025-01-05T14:06:03.677+0000] {docker.py:73} INFO - Exception encountered at "In [1]":
[2025-01-05T14:06:03.678+0000] {docker.py:73} INFO - ---------------------------------------------------------------------------
[2025-01-05T14:06:03.678+0000] {docker.py:73} INFO - PySparkRuntimeError                       Traceback (most recent call last)
[2025-01-05T14:06:03.679+0000] {docker.py:73} INFO - Cell In[1], line 41
[2025-01-05T14:06:03.680+0000] {docker.py:73} INFO -      38     builder.config(key, value)
[2025-01-05T14:06:03.680+0000] {docker.py:73} INFO -      40 # Configure Spark with Delta Lake (if needed)
[2025-01-05T14:06:03.681+0000] {docker.py:73} INFO - ---> 41 spark = configure_spark_with_delta_pip(builder).getOrCreate()
[2025-01-05T14:06:03.682+0000] {docker.py:73} INFO -      42 # Now you can use the Spark session
[2025-01-05T14:06:03.682+0000] {docker.py:73} INFO -      43 spark
[2025-01-05T14:06:03.683+0000] {docker.py:73} INFO - 
[2025-01-05T14:06:03.684+0000] {docker.py:73} INFO - File /opt/conda/lib/python3.11/site-packages/pyspark/sql/session.py:497, in SparkSession.Builder.getOrCreate(self)
[2025-01-05T14:06:03.685+0000] {docker.py:73} INFO -     495     sparkConf.set(key, value)
[2025-01-05T14:06:03.686+0000] {docker.py:73} INFO -     496 # This SparkContext may be an existing one.
[2025-01-05T14:06:03.687+0000] {docker.py:73} INFO - --> 497 sc = SparkContext.getOrCreate(sparkConf)
[2025-01-05T14:06:03.687+0000] {docker.py:73} INFO -     498 # Do not update `SparkConf` for existing `SparkContext`, as it's shared
[2025-01-05T14:06:03.688+0000] {docker.py:73} INFO -     499 # by all sessions.
[2025-01-05T14:06:03.690+0000] {docker.py:73} INFO -     500 session = SparkSession(sc, options=self._options)
[2025-01-05T14:06:03.690+0000] {docker.py:73} INFO - 
[2025-01-05T14:06:03.691+0000] {docker.py:73} INFO - File /opt/conda/lib/python3.11/site-packages/pyspark/context.py:515, in SparkContext.getOrCreate(cls, conf)
[2025-01-05T14:06:03.692+0000] {docker.py:73} INFO -     513 with SparkContext._lock:
[2025-01-05T14:06:03.693+0000] {docker.py:73} INFO -     514     if SparkContext._active_spark_context is None:
[2025-01-05T14:06:03.693+0000] {docker.py:73} INFO - --> 515         SparkContext(conf=conf or SparkConf())
[2025-01-05T14:06:03.694+0000] {docker.py:73} INFO -     516     assert SparkContext._active_spark_context is not None
[2025-01-05T14:06:03.696+0000] {docker.py:73} INFO -     517     return SparkContext._active_spark_context
[2025-01-05T14:06:03.696+0000] {docker.py:73} INFO - 
[2025-01-05T14:06:03.699+0000] {docker.py:73} INFO - File /opt/conda/lib/python3.11/site-packages/pyspark/context.py:201, in SparkContext.__init__(self, master, appName, sparkHome, pyFiles, environment, batchSize, serializer, conf, gateway, jsc, profiler_cls, udf_profiler_cls, memory_profiler_cls)
[2025-01-05T14:06:03.699+0000] {docker.py:73} INFO -     195 if gateway is not None and gateway.gateway_parameters.auth_token is None:
[2025-01-05T14:06:03.700+0000] {docker.py:73} INFO -     196     raise ValueError(
[2025-01-05T14:06:03.700+0000] {docker.py:73} INFO -     197         "You are trying to pass an insecure Py4j gateway to Spark. This"
[2025-01-05T14:06:03.702+0000] {docker.py:73} INFO -     198         " is not allowed as it is a security risk."
[2025-01-05T14:06:03.703+0000] {docker.py:73} INFO -     199     )
[2025-01-05T14:06:03.704+0000] {docker.py:73} INFO - --> 201 SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
[2025-01-05T14:06:03.704+0000] {docker.py:73} INFO -     202 try:
[2025-01-05T14:06:03.705+0000] {docker.py:73} INFO -     203     self._do_init(
[2025-01-05T14:06:03.705+0000] {docker.py:73} INFO -     204         master,
[2025-01-05T14:06:03.705+0000] {docker.py:73} INFO -     205         appName,
[2025-01-05T14:06:03.706+0000] {docker.py:73} INFO -    (...)
[2025-01-05T14:06:03.707+0000] {docker.py:73} INFO -     215         memory_profiler_cls,
[2025-01-05T14:06:03.707+0000] {docker.py:73} INFO -     216     )
[2025-01-05T14:06:03.708+0000] {docker.py:73} INFO - 
[2025-01-05T14:06:03.709+0000] {docker.py:73} INFO - File /opt/conda/lib/python3.11/site-packages/pyspark/context.py:436, in SparkContext._ensure_initialized(cls, instance, gateway, conf)
[2025-01-05T14:06:03.710+0000] {docker.py:73} INFO -     434 with SparkContext._lock:
[2025-01-05T14:06:03.710+0000] {docker.py:73} INFO -     435     if not SparkContext._gateway:
[2025-01-05T14:06:03.712+0000] {docker.py:73} INFO - --> 436         SparkContext._gateway = gateway or launch_gateway(conf)
[2025-01-05T14:06:03.713+0000] {docker.py:73} INFO -     437         SparkContext._jvm = SparkContext._gateway.jvm
[2025-01-05T14:06:03.714+0000] {docker.py:73} INFO -     439     if instance:
[2025-01-05T14:06:03.715+0000] {docker.py:73} INFO - 
[2025-01-05T14:06:03.715+0000] {docker.py:73} INFO - File /opt/conda/lib/python3.11/site-packages/pyspark/java_gateway.py:107, in launch_gateway(conf, popen_kwargs)
[2025-01-05T14:06:03.716+0000] {docker.py:73} INFO -     104     time.sleep(0.1)
[2025-01-05T14:06:03.717+0000] {docker.py:73} INFO -     106 if not os.path.isfile(conn_info_file):
[2025-01-05T14:06:03.717+0000] {docker.py:73} INFO - --> 107     raise PySparkRuntimeError(
[2025-01-05T14:06:03.718+0000] {docker.py:73} INFO -     108         error_class="JAVA_GATEWAY_EXITED",
[2025-01-05T14:06:03.719+0000] {docker.py:73} INFO -     109         message_parameters={},
[2025-01-05T14:06:03.720+0000] {docker.py:73} INFO -     110     )
[2025-01-05T14:06:03.720+0000] {docker.py:73} INFO -     112 with open(conn_info_file, "rb") as info:
[2025-01-05T14:06:03.721+0000] {docker.py:73} INFO -     113     gateway_port = read_int(info)
[2025-01-05T14:06:03.722+0000] {docker.py:73} INFO - 
[2025-01-05T14:06:03.722+0000] {docker.py:73} INFO - PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2025-01-05T14:06:03.724+0000] {docker.py:73} INFO - 
[2025-01-05T14:06:04.474+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 519, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 396, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 453, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-01-05T14:06:04.499+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dag_NB_Fetch_Google_Finance, task_id=NB_Notebook_job, run_id=manual__2025-01-05T14:05:30.215328+00:00, execution_date=20250105T140530, start_date=20250105T140533, end_date=20250105T140604
[2025-01-05T14:06:04.540+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-05T14:06:04.542+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 603 for task NB_Notebook_job (Docker container failed: {'StatusCode': 1}; 377)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 519, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 396, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 453, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-01-05T14:06:04.625+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-05T14:06:04.701+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-05T14:06:04.705+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
