[2024-12-21T09:03:09.853+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-21T09:03:09.870+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: docker_dag.Notebook_job manual__2024-12-21T09:02:38.071328+00:00 [queued]>
[2024-12-21T09:03:09.879+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: docker_dag.Notebook_job manual__2024-12-21T09:02:38.071328+00:00 [queued]>
[2024-12-21T09:03:09.880+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-21T09:03:09.898+0000] {taskinstance.py:2889} INFO - Executing <Task(DockerOperator): Notebook_job> on 2024-12-21 09:02:38.071328+00:00
[2024-12-21T09:03:09.914+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=897) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-21T09:03:09.916+0000] {standard_task_runner.py:72} INFO - Started process 898 to run task
[2024-12-21T09:03:09.917+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'docker_dag', 'Notebook_job', 'manual__2024-12-21T09:02:38.071328+00:00', '--job-id', '116', '--raw', '--subdir', 'DAGS_FOLDER/A_dag_test.py', '--cfg-path', '/tmp/tmpkmsn3flt']
[2024-12-21T09:03:09.919+0000] {standard_task_runner.py:105} INFO - Job 116: Subtask Notebook_job
[2024-12-21T09:03:09.964+0000] {task_command.py:467} INFO - Running <TaskInstance: docker_dag.Notebook_job manual__2024-12-21T09:02:38.071328+00:00 [running]> on host eb868d70c2c6
[2024-12-21T09:03:10.076+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='docker_dag' AIRFLOW_CTX_TASK_ID='Notebook_job' AIRFLOW_CTX_EXECUTION_DATE='2024-12-21T09:02:38.071328+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-21T09:02:38.071328+00:00'
[2024-12-21T09:03:10.080+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-21T09:03:10.080+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-21T09:03:10.081+0000] {logging_mixin.py:190} INFO - Current task name:Notebook_job state:running start_date:2024-12-21 09:03:09.871298+00:00
[2024-12-21T09:03:10.081+0000] {logging_mixin.py:190} INFO - Dag name:docker_dag and current dag run status:running
[2024-12-21T09:03:10.082+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-21T09:03:10.372+0000] {docker.py:379} INFO - Starting docker container from image spark-cluster:version-1.0.0
[2024-12-21T09:03:13.154+0000] {docker.py:73} INFO - Input Notebook:  /home/jovyan/Notebooks/NB_Calendar.ipynb
[2024-12-21T09:03:13.164+0000] {docker.py:73} INFO - Output Notebook: /home/jovyan/Notebooks/output-NB_Calendar.ipynb
[2024-12-21T09:03:13.167+0000] {docker.py:73} INFO - Traceback (most recent call last):
[2024-12-21T09:03:13.170+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/papermill/iorw.py", line 199, in read
[2024-12-21T09:03:13.170+0000] {docker.py:73} INFO -     json.loads(path)
[2024-12-21T09:03:13.173+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/json/__init__.py", line 346, in loads
[2024-12-21T09:03:13.173+0000] {docker.py:73} INFO -     return _default_decoder.decode(s)
[2024-12-21T09:03:13.173+0000] {docker.py:73} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-21T09:03:13.174+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/json/decoder.py", line 337, in decode
[2024-12-21T09:03:13.175+0000] {docker.py:73} INFO -     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
[2024-12-21T09:03:13.175+0000] {docker.py:73} INFO -                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-21T09:03:13.175+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/json/decoder.py", line 355, in raw_decode
[2024-12-21T09:03:13.176+0000] {docker.py:73} INFO -     raise JSONDecodeError("Expecting value", s, err.value) from None
[2024-12-21T09:03:13.176+0000] {docker.py:73} INFO - json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-12-21T09:03:13.177+0000] {docker.py:73} INFO - 
[2024-12-21T09:03:13.177+0000] {docker.py:73} INFO - During handling of the above exception, another exception occurred:
[2024-12-21T09:03:13.177+0000] {docker.py:73} INFO - 
[2024-12-21T09:03:13.177+0000] {docker.py:73} INFO - Traceback (most recent call last):
[2024-12-21T09:03:13.178+0000] {docker.py:73} INFO -   File "/opt/conda/bin/papermill", line 8, in <module>
[2024-12-21T09:03:13.179+0000] {docker.py:73} INFO -     sys.exit(papermill())
[2024-12-21T09:03:13.179+0000] {docker.py:73} INFO -              ^^^^^^^^^^^
[2024-12-21T09:03:13.179+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
[2024-12-21T09:03:13.182+0000] {docker.py:73} INFO -     return self.main(*args, **kwargs)
[2024-12-21T09:03:13.185+0000] {docker.py:73} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-21T09:03:13.186+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 1078, in main
[2024-12-21T09:03:13.189+0000] {docker.py:73} INFO -     rv = self.invoke(ctx)
[2024-12-21T09:03:13.191+0000] {docker.py:73} INFO -          ^^^^^^^^^^^^^^^^
[2024-12-21T09:03:13.193+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
[2024-12-21T09:03:13.194+0000] {docker.py:73} INFO -     return ctx.invoke(self.callback, **ctx.params)
[2024-12-21T09:03:13.194+0000] {docker.py:73} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-21T09:03:13.194+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 783, in invoke
[2024-12-21T09:03:13.194+0000] {docker.py:73} INFO -     return __callback(*args, **kwargs)
[2024-12-21T09:03:13.195+0000] {docker.py:73} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-21T09:03:13.195+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
[2024-12-21T09:03:13.195+0000] {docker.py:73} INFO -     return f(get_current_context(), *args, **kwargs)
[2024-12-21T09:03:13.195+0000] {docker.py:73} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-21T09:03:13.196+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/papermill/cli.py", line 235, in papermill
[2024-12-21T09:03:13.196+0000] {docker.py:73} INFO -     execute_notebook(
[2024-12-21T09:03:13.196+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/papermill/execute.py", line 89, in execute_notebook
[2024-12-21T09:03:13.196+0000] {docker.py:73} INFO -     nb = load_notebook_node(input_path)
[2024-12-21T09:03:13.196+0000] {docker.py:73} INFO -          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-21T09:03:13.197+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/papermill/iorw.py", line 499, in load_notebook_node
[2024-12-21T09:03:13.197+0000] {docker.py:73} INFO -     nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
[2024-12-21T09:03:13.197+0000] {docker.py:73} INFO -                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-21T09:03:13.197+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/papermill/iorw.py", line 96, in read
[2024-12-21T09:03:13.199+0000] {docker.py:73} INFO -     notebook_metadata = self.get_handler(path, extensions).read(path)
[2024-12-21T09:03:13.199+0000] {docker.py:73} INFO -                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-21T09:03:13.199+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/papermill/iorw.py", line 203, in read
[2024-12-21T09:03:13.200+0000] {docker.py:73} INFO -     raise e
[2024-12-21T09:03:13.200+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/papermill/iorw.py", line 193, in read
[2024-12-21T09:03:13.200+0000] {docker.py:73} INFO -     with open(path, encoding="utf-8") as f:
[2024-12-21T09:03:13.200+0000] {docker.py:73} INFO -          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-21T09:03:13.201+0000] {docker.py:73} INFO - FileNotFoundError: [Errno 2] No such file or directory: '/home/jovyan/Notebooks/NB_Calendar.ipynb'
[2024-12-21T09:03:13.824+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 519, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 396, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 453, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2024-12-21T09:03:13.848+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-21T09:03:13.848+0000] {logging_mixin.py:190} INFO - Task start:2024-12-21 09:03:09.871298+00:00 end:2024-12-21 09:03:13.838880+00:00 duration:3.967582
[2024-12-21T09:03:13.849+0000] {logging_mixin.py:190} INFO - Task:<Task(DockerOperator): Notebook_job> dag:<DAG: docker_dag> dagrun:<DagRun docker_dag @ 2024-12-21 09:02:38.071328+00:00: manual__2024-12-21T09:02:38.071328+00:00, state:running, queued_at: 2024-12-21 09:02:38.117092+00:00. externally triggered: True>
[2024-12-21T09:03:13.850+0000] {logging_mixin.py:190} INFO - Failure caused by Docker container failed: {'StatusCode': 1}
[2024-12-21T09:03:13.850+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=docker_dag, task_id=Notebook_job, run_id=manual__2024-12-21T09:02:38.071328+00:00, execution_date=20241221T090238, start_date=20241221T090309, end_date=20241221T090313
[2024-12-21T09:03:13.918+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-21T09:03:13.920+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 116 for task Notebook_job (Docker container failed: {'StatusCode': 1}; 898)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 519, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 396, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 453, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2024-12-21T09:03:14.060+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-21T09:03:14.206+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-21T09:03:14.214+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
