[2024-12-21T11:32:22.033+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-21T11:32:22.042+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: docker_dag.start_spark manual__2024-12-21T11:32:20.463976+00:00 [queued]>
[2024-12-21T11:32:22.045+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: docker_dag.start_spark manual__2024-12-21T11:32:20.463976+00:00 [queued]>
[2024-12-21T11:32:22.046+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-21T11:32:22.051+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): start_spark> on 2024-12-21 11:32:20.463976+00:00
[2024-12-21T11:32:22.058+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=165) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-21T11:32:22.060+0000] {standard_task_runner.py:72} INFO - Started process 166 to run task
[2024-12-21T11:32:22.060+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'docker_dag', 'start_spark', 'manual__2024-12-21T11:32:20.463976+00:00', '--job-id', '127', '--raw', '--subdir', 'DAGS_FOLDER/A_dag_test.py', '--cfg-path', '/tmp/tmpe2lxg5l6']
[2024-12-21T11:32:22.061+0000] {standard_task_runner.py:105} INFO - Job 127: Subtask start_spark
[2024-12-21T11:32:22.094+0000] {task_command.py:467} INFO - Running <TaskInstance: docker_dag.start_spark manual__2024-12-21T11:32:20.463976+00:00 [running]> on host 35879d62dcc5
[2024-12-21T11:32:22.138+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='docker_dag' AIRFLOW_CTX_TASK_ID='start_spark' AIRFLOW_CTX_EXECUTION_DATE='2024-12-21T11:32:20.463976+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-21T11:32:20.463976+00:00'
[2024-12-21T11:32:22.139+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-21T11:32:22.139+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-21T11:32:22.139+0000] {logging_mixin.py:190} INFO - Current task name:start_spark state:running start_date:2024-12-21 11:32:22.042492+00:00
[2024-12-21T11:32:22.139+0000] {logging_mixin.py:190} INFO - Dag name:docker_dag and current dag run status:running
[2024-12-21T11:32:22.140+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-21T11:32:22.140+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2024-12-21T11:32:22.141+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'bash /opt/***/dags/cluster.sh start']
[2024-12-21T11:32:22.147+0000] {subprocess.py:99} INFO - Output:
[2024-12-21T11:32:22.150+0000] {subprocess.py:106} INFO - Starting the cluster...
[2024-12-21T11:32:22.165+0000] {subprocess.py:106} INFO - docker: 'compose' is not a docker command.
[2024-12-21T11:32:22.166+0000] {subprocess.py:106} INFO - See 'docker --help'
[2024-12-21T11:32:22.166+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2024-12-21T11:32:22.174+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-12-21T11:32:22.177+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-21T11:32:22.178+0000] {logging_mixin.py:190} INFO - Task start:2024-12-21 11:32:22.042492+00:00 end:2024-12-21 11:32:22.177316+00:00 duration:0.134824
[2024-12-21T11:32:22.178+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): start_spark> dag:<DAG: docker_dag> dagrun:<DagRun docker_dag @ 2024-12-21 11:32:20.463976+00:00: manual__2024-12-21T11:32:20.463976+00:00, state:running, queued_at: 2024-12-21 11:32:20.492240+00:00. externally triggered: True>
[2024-12-21T11:32:22.178+0000] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 1.
[2024-12-21T11:32:22.178+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=docker_dag, task_id=start_spark, run_id=manual__2024-12-21T11:32:20.463976+00:00, execution_date=20241221T113220, start_date=20241221T113222, end_date=20241221T113222
[2024-12-21T11:32:22.186+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-21T11:32:22.187+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 127 for task start_spark (Bash command failed. The command returned a non-zero exit code 1.; 166)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-12-21T11:32:22.202+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-21T11:32:22.219+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-21T11:32:22.223+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
