[2024-12-22T13:12:12.321+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-22T13:12:12.340+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: docker_dag.Notebook_job scheduled__2024-12-21T00:00:00+00:00 [queued]>
[2024-12-22T13:12:12.361+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: docker_dag.Notebook_job scheduled__2024-12-21T00:00:00+00:00 [queued]>
[2024-12-22T13:12:12.363+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-22T13:12:12.382+0000] {taskinstance.py:2889} INFO - Executing <Task(DockerOperator): Notebook_job> on 2024-12-21 00:00:00+00:00
[2024-12-22T13:12:12.414+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=70) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-22T13:12:12.417+0000] {standard_task_runner.py:72} INFO - Started process 71 to run task
[2024-12-22T13:12:12.416+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'docker_dag', 'Notebook_job', 'scheduled__2024-12-21T00:00:00+00:00', '--job-id', '148', '--raw', '--subdir', 'DAGS_FOLDER/A_dag_test.py', '--cfg-path', '/tmp/tmpk43x6c1e']
[2024-12-22T13:12:12.418+0000] {standard_task_runner.py:105} INFO - Job 148: Subtask Notebook_job
[2024-12-22T13:12:12.498+0000] {task_command.py:467} INFO - Running <TaskInstance: docker_dag.Notebook_job scheduled__2024-12-21T00:00:00+00:00 [running]> on host 49ab4fbc6be0
[2024-12-22T13:12:12.663+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='docker_dag' AIRFLOW_CTX_TASK_ID='Notebook_job' AIRFLOW_CTX_EXECUTION_DATE='2024-12-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-21T00:00:00+00:00'
[2024-12-22T13:12:12.665+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-22T13:12:12.666+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-22T13:12:12.666+0000] {logging_mixin.py:190} INFO - Current task name:Notebook_job state:running start_date:2024-12-22 13:12:12.341336+00:00
[2024-12-22T13:12:12.667+0000] {logging_mixin.py:190} INFO - Dag name:docker_dag and current dag run status:running
[2024-12-22T13:12:12.667+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-22T13:12:13.064+0000] {docker.py:379} INFO - Starting docker container from image spark-cluster:version-1.0.0
[2024-12-22T13:12:15.611+0000] {docker.py:73} INFO - Input Notebook:  /home/jovyan/Notebooks/NB_Calendar.ipynb
[2024-12-22T13:12:15.622+0000] {docker.py:73} INFO - Output Notebook: /home/jovyan/Notebooks/output-NB_Calendar.ipynb
[2024-12-22T13:12:15.684+0000] {docker.py:73} INFO - Executing:   0%|          | 0/14 [00:00<?, ?cell/s]
[2024-12-22T13:12:17.180+0000] {docker.py:73} INFO - Executing notebook with kernel: python3
[2024-12-22T13:12:18.080+0000] {docker.py:73} INFO - Executing:   7%|▋         | 1/14 [00:02<00:31,  2.39s/cell]
[2024-12-22T13:12:19.344+0000] {docker.py:73} INFO - :: loading settings :: url = jar:file:/usr/local/spark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2024-12-22T13:12:19.400+0000] {docker.py:73} INFO - Ivy Default Cache set to: /home/jovyan/.ivy2/cache
[2024-12-22T13:12:19.401+0000] {docker.py:73} INFO - The jars for the packages stored in: /home/jovyan/.ivy2/jars
[2024-12-22T13:12:19.404+0000] {docker.py:73} INFO - io.delta#delta-spark_2.12 added as a dependency
[2024-12-22T13:12:19.405+0000] {docker.py:73} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-8c572723-426b-4ace-bfea-357e02210241;1.0
[2024-12-22T13:12:19.405+0000] {docker.py:73} INFO - 	confs: [default]
[2024-12-22T13:12:35.593+0000] {docker.py:73} INFO - :: resolution report :: resolve 16185ms :: artifacts dl 0ms
[2024-12-22T13:12:35.603+0000] {docker.py:73} INFO - 	:: modules in use:
[2024-12-22T13:12:35.604+0000] {docker.py:73} INFO - 	---------------------------------------------------------------------
[2024-12-22T13:12:35.604+0000] {docker.py:73} INFO - 	|                  |            modules            ||   artifacts   |
[2024-12-22T13:12:35.604+0000] {docker.py:73} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2024-12-22T13:12:35.605+0000] {docker.py:73} INFO - 	---------------------------------------------------------------------
[2024-12-22T13:12:35.605+0000] {docker.py:73} INFO - 	|      default     |   1   |   0   |   0   |   0   ||   0   |   0   |
[2024-12-22T13:12:35.606+0000] {docker.py:73} INFO - 	---------------------------------------------------------------------
[2024-12-22T13:12:35.606+0000] {docker.py:73} INFO - 
[2024-12-22T13:12:35.606+0000] {docker.py:73} INFO - :: problems summary ::
[2024-12-22T13:12:35.606+0000] {docker.py:73} INFO - :::: WARNINGS
[2024-12-22T13:12:35.607+0000] {docker.py:73} INFO - 		module not found: io.delta#delta-spark_2.12;3.1.0
[2024-12-22T13:12:35.607+0000] {docker.py:73} INFO - 
[2024-12-22T13:12:35.607+0000] {docker.py:73} INFO - 	==== local-m2-cache: tried
[2024-12-22T13:12:35.607+0000] {docker.py:73} INFO - 
[2024-12-22T13:12:35.607+0000] {docker.py:73} INFO - 	  file:/home/jovyan/.m2/repository/io/delta/delta-spark_2.12/3.1.0/delta-spark_2.12-3.1.0.pom
[2024-12-22T13:12:35.608+0000] {docker.py:73} INFO - 
[2024-12-22T13:12:35.608+0000] {docker.py:73} INFO - 	  -- artifact io.delta#delta-spark_2.12;3.1.0!delta-spark_2.12.jar:
[2024-12-22T13:12:35.608+0000] {docker.py:73} INFO - 
[2024-12-22T13:12:35.608+0000] {docker.py:73} INFO - 	  file:/home/jovyan/.m2/repository/io/delta/delta-spark_2.12/3.1.0/delta-spark_2.12-3.1.0.jar
[2024-12-22T13:12:35.608+0000] {docker.py:73} INFO - 
[2024-12-22T13:12:35.609+0000] {docker.py:73} INFO - 	==== local-ivy-cache: tried
[2024-12-22T13:12:35.609+0000] {docker.py:73} INFO - 
[2024-12-22T13:12:35.609+0000] {docker.py:73} INFO - 	  /home/jovyan/.ivy2/local/io.delta/delta-spark_2.12/3.1.0/ivys/ivy.xml
[2024-12-22T13:12:35.609+0000] {docker.py:73} INFO - 
[2024-12-22T13:12:35.609+0000] {docker.py:73} INFO - 	  -- artifact io.delta#delta-spark_2.12;3.1.0!delta-spark_2.12.jar:
[2024-12-22T13:12:35.610+0000] {docker.py:73} INFO - 
[2024-12-22T13:12:35.610+0000] {docker.py:73} INFO - 	  /home/jovyan/.ivy2/local/io.delta/delta-spark_2.12/3.1.0/jars/delta-spark_2.12.jar
[2024-12-22T13:12:35.610+0000] {docker.py:73} INFO - 
[2024-12-22T13:12:35.611+0000] {docker.py:73} INFO - 	==== central: tried
[2024-12-22T13:12:35.611+0000] {docker.py:73} INFO - 
[2024-12-22T13:12:35.612+0000] {docker.py:73} INFO - 	  https://repo1.maven.org/maven2/io/delta/delta-spark_2.12/3.1.0/delta-spark_2.12-3.1.0.pom
[2024-12-22T13:12:35.612+0000] {docker.py:73} INFO - 
[2024-12-22T13:12:35.612+0000] {docker.py:73} INFO - 	  -- artifact io.delta#delta-spark_2.12;3.1.0!delta-spark_2.12.jar:
[2024-12-22T13:12:35.613+0000] {docker.py:73} INFO - 
[2024-12-22T13:12:35.613+0000] {docker.py:73} INFO - 	  https://repo1.maven.org/maven2/io/delta/delta-spark_2.12/3.1.0/delta-spark_2.12-3.1.0.jar
[2024-12-22T13:12:35.614+0000] {docker.py:73} INFO - 
[2024-12-22T13:12:35.615+0000] {docker.py:73} INFO - 	==== spark-packages: tried
[2024-12-22T13:12:35.615+0000] {docker.py:73} INFO - 
[2024-12-22T13:12:35.615+0000] {docker.py:73} INFO - 	  https://repos.spark-packages.org/io/delta/delta-spark_2.12/3.1.0/delta-spark_2.12-3.1.0.pom
[2024-12-22T13:12:35.616+0000] {docker.py:73} INFO - 
[2024-12-22T13:12:35.616+0000] {docker.py:73} INFO - 	  -- artifact io.delta#delta-spark_2.12;3.1.0!delta-spark_2.12.jar:
[2024-12-22T13:12:35.617+0000] {docker.py:73} INFO - 
[2024-12-22T13:12:35.617+0000] {docker.py:73} INFO - 	  https://repos.spark-packages.org/io/delta/delta-spark_2.12/3.1.0/delta-spark_2.12-3.1.0.jar
[2024-12-22T13:12:35.617+0000] {docker.py:73} INFO - 
[2024-12-22T13:12:35.617+0000] {docker.py:73} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2024-12-22T13:12:35.618+0000] {docker.py:73} INFO - 
[2024-12-22T13:12:35.618+0000] {docker.py:73} INFO - 		::          UNRESOLVED DEPENDENCIES         ::
[2024-12-22T13:12:35.618+0000] {docker.py:73} INFO - 
[2024-12-22T13:12:35.619+0000] {docker.py:73} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2024-12-22T13:12:35.619+0000] {docker.py:73} INFO - 
[2024-12-22T13:12:35.619+0000] {docker.py:73} INFO - 		:: io.delta#delta-spark_2.12;3.1.0: not found
[2024-12-22T13:12:35.619+0000] {docker.py:73} INFO - 
[2024-12-22T13:12:35.620+0000] {docker.py:73} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2024-12-22T13:12:35.620+0000] {docker.py:73} INFO - 
[2024-12-22T13:12:35.620+0000] {docker.py:73} INFO - 
[2024-12-22T13:12:35.620+0000] {docker.py:73} INFO - :::: ERRORS
[2024-12-22T13:12:35.621+0000] {docker.py:73} INFO - 	Server access error at url https://repo1.maven.org/maven2/io/delta/delta-spark_2.12/3.1.0/delta-spark_2.12-3.1.0.pom (java.net.ConnectException: Connection refused)
[2024-12-22T13:12:35.621+0000] {docker.py:73} INFO - 	Server access error at url https://repo1.maven.org/maven2/io/delta/delta-spark_2.12/3.1.0/delta-spark_2.12-3.1.0.jar (java.net.ConnectException: Connection refused)
[2024-12-22T13:12:35.621+0000] {docker.py:73} INFO - 
[2024-12-22T13:12:35.621+0000] {docker.py:73} INFO - 
[2024-12-22T13:12:35.621+0000] {docker.py:73} INFO - :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
[2024-12-22T13:12:35.621+0000] {docker.py:73} INFO - Exception in thread "main"
[2024-12-22T13:12:35.622+0000] {docker.py:73} INFO - java.lang.RuntimeException: [unresolved dependency: io.delta#delta-spark_2.12;3.1.0: not found]
[2024-12-22T13:12:35.622+0000] {docker.py:73} INFO - 	at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1537)
[2024-12-22T13:12:35.622+0000] {docker.py:73} INFO - 	at org.apache.spark.util.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:185)
[2024-12-22T13:12:35.622+0000] {docker.py:73} INFO - 	at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:334)
[2024-12-22T13:12:35.622+0000] {docker.py:73} INFO - 	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:964)
[2024-12-22T13:12:35.622+0000] {docker.py:73} INFO - 	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:194)
[2024-12-22T13:12:35.623+0000] {docker.py:73} INFO - 	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:217)
[2024-12-22T13:12:35.623+0000] {docker.py:73} INFO - 	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:91)
[2024-12-22T13:12:35.623+0000] {docker.py:73} INFO - 	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1120)
[2024-12-22T13:12:35.623+0000] {docker.py:73} INFO - 	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1129)
[2024-12-22T13:12:35.624+0000] {docker.py:73} INFO - 	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2024-12-22T13:12:36.175+0000] {docker.py:73} INFO - Executing:  21%|██▏       | 3/14 [00:20<01:20,  7.32s/cell]
[2024-12-22T13:12:36.606+0000] {docker.py:73} INFO - Executing:  21%|██▏       | 3/14 [00:20<01:16,  6.97s/cell]
[2024-12-22T13:12:36.612+0000] {docker.py:73} INFO - Traceback (most recent call last):
[2024-12-22T13:12:36.614+0000] {docker.py:73} INFO -   File "/opt/conda/bin/papermill", line 8, in <module>
[2024-12-22T13:12:36.616+0000] {docker.py:73} INFO -     sys.exit(papermill())
[2024-12-22T13:12:36.618+0000] {docker.py:73} INFO -              ^^^^^^^^^^^
[2024-12-22T13:12:36.618+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
[2024-12-22T13:12:36.619+0000] {docker.py:73} INFO -     return self.main(*args, **kwargs)
[2024-12-22T13:12:36.621+0000] {docker.py:73} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-22T13:12:36.621+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 1078, in main
[2024-12-22T13:12:36.622+0000] {docker.py:73} INFO -     rv = self.invoke(ctx)
[2024-12-22T13:12:36.623+0000] {docker.py:73} INFO -          ^^^^^^^^^^^^^^^^
[2024-12-22T13:12:36.624+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
[2024-12-22T13:12:36.625+0000] {docker.py:73} INFO -     return ctx.invoke(self.callback, **ctx.params)
[2024-12-22T13:12:36.626+0000] {docker.py:73} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-22T13:12:36.627+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 783, in invoke
[2024-12-22T13:12:36.628+0000] {docker.py:73} INFO -     return __callback(*args, **kwargs)
[2024-12-22T13:12:36.629+0000] {docker.py:73} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-22T13:12:36.629+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
[2024-12-22T13:12:36.630+0000] {docker.py:73} INFO -     return f(get_current_context(), *args, **kwargs)
[2024-12-22T13:12:36.630+0000] {docker.py:73} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-22T13:12:36.630+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/papermill/cli.py", line 235, in papermill
[2024-12-22T13:12:36.631+0000] {docker.py:73} INFO -     execute_notebook(
[2024-12-22T13:12:36.631+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/papermill/execute.py", line 131, in execute_notebook
[2024-12-22T13:12:36.632+0000] {docker.py:73} INFO -     raise_for_execution_errors(nb, output_path)
[2024-12-22T13:12:36.632+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/papermill/execute.py", line 251, in raise_for_execution_errors
[2024-12-22T13:12:36.633+0000] {docker.py:73} INFO -     raise error
[2024-12-22T13:12:36.633+0000] {docker.py:73} INFO - papermill.exceptions.PapermillExecutionError: 
[2024-12-22T13:12:36.634+0000] {docker.py:73} INFO - ---------------------------------------------------------------------------
[2024-12-22T13:12:36.634+0000] {docker.py:73} INFO - Exception encountered at "In [3]":
[2024-12-22T13:12:36.634+0000] {docker.py:73} INFO - ---------------------------------------------------------------------------
[2024-12-22T13:12:36.635+0000] {docker.py:73} INFO - PySparkRuntimeError                       Traceback (most recent call last)
[2024-12-22T13:12:36.636+0000] {docker.py:73} INFO - Cell In[3], line 2
[2024-12-22T13:12:36.636+0000] {docker.py:73} INFO -       1 # Configure Spark with Delta Lake (if needed)
[2024-12-22T13:12:36.637+0000] {docker.py:73} INFO - ----> 2 spark = configure_spark_with_delta_pip(builder).getOrCreate()
[2024-12-22T13:12:36.637+0000] {docker.py:73} INFO -       4 driver_version = sys.version_info
[2024-12-22T13:12:36.638+0000] {docker.py:73} INFO -       5 worker_version = spark.sparkContext.pythonExec
[2024-12-22T13:12:36.638+0000] {docker.py:73} INFO - 
[2024-12-22T13:12:36.639+0000] {docker.py:73} INFO - File /opt/conda/lib/python3.11/site-packages/pyspark/sql/session.py:497, in SparkSession.Builder.getOrCreate(self)
[2024-12-22T13:12:36.639+0000] {docker.py:73} INFO -     495     sparkConf.set(key, value)
[2024-12-22T13:12:36.642+0000] {docker.py:73} INFO -     496 # This SparkContext may be an existing one.
[2024-12-22T13:12:36.642+0000] {docker.py:73} INFO - --> 497 sc = SparkContext.getOrCreate(sparkConf)
[2024-12-22T13:12:36.643+0000] {docker.py:73} INFO -     498 # Do not update `SparkConf` for existing `SparkContext`, as it's shared
[2024-12-22T13:12:36.644+0000] {docker.py:73} INFO -     499 # by all sessions.
[2024-12-22T13:12:36.645+0000] {docker.py:73} INFO -     500 session = SparkSession(sc, options=self._options)
[2024-12-22T13:12:36.646+0000] {docker.py:73} INFO - 
[2024-12-22T13:12:36.647+0000] {docker.py:73} INFO - File /opt/conda/lib/python3.11/site-packages/pyspark/context.py:515, in SparkContext.getOrCreate(cls, conf)
[2024-12-22T13:12:36.648+0000] {docker.py:73} INFO -     513 with SparkContext._lock:
[2024-12-22T13:12:36.648+0000] {docker.py:73} INFO -     514     if SparkContext._active_spark_context is None:
[2024-12-22T13:12:36.649+0000] {docker.py:73} INFO - --> 515         SparkContext(conf=conf or SparkConf())
[2024-12-22T13:12:36.650+0000] {docker.py:73} INFO -     516     assert SparkContext._active_spark_context is not None
[2024-12-22T13:12:36.651+0000] {docker.py:73} INFO -     517     return SparkContext._active_spark_context
[2024-12-22T13:12:36.652+0000] {docker.py:73} INFO - 
[2024-12-22T13:12:36.653+0000] {docker.py:73} INFO - File /opt/conda/lib/python3.11/site-packages/pyspark/context.py:201, in SparkContext.__init__(self, master, appName, sparkHome, pyFiles, environment, batchSize, serializer, conf, gateway, jsc, profiler_cls, udf_profiler_cls, memory_profiler_cls)
[2024-12-22T13:12:36.654+0000] {docker.py:73} INFO -     195 if gateway is not None and gateway.gateway_parameters.auth_token is None:
[2024-12-22T13:12:36.655+0000] {docker.py:73} INFO -     196     raise ValueError(
[2024-12-22T13:12:36.656+0000] {docker.py:73} INFO -     197         "You are trying to pass an insecure Py4j gateway to Spark. This"
[2024-12-22T13:12:36.657+0000] {docker.py:73} INFO -     198         " is not allowed as it is a security risk."
[2024-12-22T13:12:36.658+0000] {docker.py:73} INFO -     199     )
[2024-12-22T13:12:36.659+0000] {docker.py:73} INFO - --> 201 SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
[2024-12-22T13:12:36.659+0000] {docker.py:73} INFO -     202 try:
[2024-12-22T13:12:36.660+0000] {docker.py:73} INFO -     203     self._do_init(
[2024-12-22T13:12:36.661+0000] {docker.py:73} INFO -     204         master,
[2024-12-22T13:12:36.662+0000] {docker.py:73} INFO -     205         appName,
[2024-12-22T13:12:36.662+0000] {docker.py:73} INFO -    (...)
[2024-12-22T13:12:36.663+0000] {docker.py:73} INFO -     215         memory_profiler_cls,
[2024-12-22T13:12:36.663+0000] {docker.py:73} INFO -     216     )
[2024-12-22T13:12:36.664+0000] {docker.py:73} INFO - 
[2024-12-22T13:12:36.664+0000] {docker.py:73} INFO - File /opt/conda/lib/python3.11/site-packages/pyspark/context.py:436, in SparkContext._ensure_initialized(cls, instance, gateway, conf)
[2024-12-22T13:12:36.665+0000] {docker.py:73} INFO -     434 with SparkContext._lock:
[2024-12-22T13:12:36.665+0000] {docker.py:73} INFO -     435     if not SparkContext._gateway:
[2024-12-22T13:12:36.666+0000] {docker.py:73} INFO - --> 436         SparkContext._gateway = gateway or launch_gateway(conf)
[2024-12-22T13:12:36.666+0000] {docker.py:73} INFO -     437         SparkContext._jvm = SparkContext._gateway.jvm
[2024-12-22T13:12:36.667+0000] {docker.py:73} INFO -     439     if instance:
[2024-12-22T13:12:36.667+0000] {docker.py:73} INFO - 
[2024-12-22T13:12:36.667+0000] {docker.py:73} INFO - File /opt/conda/lib/python3.11/site-packages/pyspark/java_gateway.py:107, in launch_gateway(conf, popen_kwargs)
[2024-12-22T13:12:36.668+0000] {docker.py:73} INFO -     104     time.sleep(0.1)
[2024-12-22T13:12:36.669+0000] {docker.py:73} INFO -     106 if not os.path.isfile(conn_info_file):
[2024-12-22T13:12:36.669+0000] {docker.py:73} INFO - --> 107     raise PySparkRuntimeError(
[2024-12-22T13:12:36.670+0000] {docker.py:73} INFO -     108         error_class="JAVA_GATEWAY_EXITED",
[2024-12-22T13:12:36.670+0000] {docker.py:73} INFO -     109         message_parameters={},
[2024-12-22T13:12:36.671+0000] {docker.py:73} INFO -     110     )
[2024-12-22T13:12:36.671+0000] {docker.py:73} INFO -     112 with open(conn_info_file, "rb") as info:
[2024-12-22T13:12:36.671+0000] {docker.py:73} INFO -     113     gateway_port = read_int(info)
[2024-12-22T13:12:36.672+0000] {docker.py:73} INFO - 
[2024-12-22T13:12:36.672+0000] {docker.py:73} INFO - PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-12-22T13:12:37.215+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 519, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 396, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 453, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2024-12-22T13:12:37.235+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-22T13:12:37.236+0000] {logging_mixin.py:190} INFO - Task start:2024-12-22 13:12:12.341336+00:00 end:2024-12-22 13:12:37.232217+00:00 duration:24.890881
[2024-12-22T13:12:37.237+0000] {logging_mixin.py:190} INFO - Task:<Task(DockerOperator): Notebook_job> dag:<DAG: docker_dag> dagrun:<DagRun docker_dag @ 2024-12-21 00:00:00+00:00: scheduled__2024-12-21T00:00:00+00:00, state:running, queued_at: 2024-12-22 13:12:01.101420+00:00. externally triggered: False>
[2024-12-22T13:12:37.237+0000] {logging_mixin.py:190} INFO - Failure caused by Docker container failed: {'StatusCode': 1}
[2024-12-22T13:12:37.238+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=docker_dag, task_id=Notebook_job, run_id=scheduled__2024-12-21T00:00:00+00:00, execution_date=20241221T000000, start_date=20241222T131212, end_date=20241222T131237
[2024-12-22T13:12:37.270+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-22T13:12:37.272+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 148 for task Notebook_job (Docker container failed: {'StatusCode': 1}; 71)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 519, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 396, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 453, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2024-12-22T13:12:37.351+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-22T13:12:37.403+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-22T13:12:37.406+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-22T13:12:37.436+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
