[2024-12-23T18:53:24.744+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-23T18:53:24.785+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_Category_NTBK.NB_Notebook_job manual__2024-12-23T18:53:18.419471+00:00 [queued]>
[2024-12-23T18:53:24.801+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_Category_NTBK.NB_Notebook_job manual__2024-12-23T18:53:18.419471+00:00 [queued]>
[2024-12-23T18:53:24.802+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-23T18:53:24.821+0000] {taskinstance.py:2889} INFO - Executing <Task(DockerOperator): NB_Notebook_job> on 2024-12-23 18:53:18.419471+00:00
[2024-12-23T18:53:24.854+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_Category_NTBK', 'NB_Notebook_job', 'manual__2024-12-23T18:53:18.419471+00:00', '--job-id', '268', '--raw', '--subdir', 'DAGS_FOLDER/dag_category.py', '--cfg-path', '/tmp/tmp9u6xyxkg']
[2024-12-23T18:53:24.847+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1789) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-23T18:53:24.860+0000] {standard_task_runner.py:105} INFO - Job 268: Subtask NB_Notebook_job
[2024-12-23T18:53:24.861+0000] {standard_task_runner.py:72} INFO - Started process 1791 to run task
[2024-12-23T18:53:25.208+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_Category_NTBK.NB_Notebook_job manual__2024-12-23T18:53:18.419471+00:00 [running]> on host 39871ab9c276
[2024-12-23T18:53:25.612+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_Category_NTBK' AIRFLOW_CTX_TASK_ID='NB_Notebook_job' AIRFLOW_CTX_EXECUTION_DATE='2024-12-23T18:53:18.419471+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-23T18:53:18.419471+00:00'
[2024-12-23T18:53:25.626+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-23T18:53:26.470+0000] {docker.py:379} INFO - Starting docker container from image spark-cluster:version-1.0.0
[2024-12-23T18:53:43.419+0000] {docker.py:73} INFO - Input Notebook:  /home/jovyan/Notebooks/NB_DIM_Category.ipynb
[2024-12-23T18:53:43.451+0000] {docker.py:73} INFO - Output Notebook: /home/jovyan/Notebooks/output-NB_DIM_Category.ipynb
[2024-12-23T18:53:44.359+0000] {docker.py:73} INFO - Executing:   0%|          | 0/13 [00:00<?, ?cell/s]
[2024-12-23T18:54:08.059+0000] {docker.py:73} INFO - Executing notebook with kernel: python3
[2024-12-23T18:54:23.651+0000] {docker.py:73} INFO - Executing:   8%|▊         | 1/13 [00:39<07:52, 39.36s/cell]
[2024-12-23T18:54:23.770+0000] {docker.py:73} INFO - Executing:  15%|█▌        | 2/13 [00:39<02:59, 16.29s/cell]
[2024-12-23T18:54:36.807+0000] {docker.py:73} INFO - :: loading settings :: url = jar:file:/usr/local/spark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2024-12-23T18:54:36.927+0000] {docker.py:73} INFO - Ivy Default Cache set to: /home/jovyan/.ivy2/cache
[2024-12-23T18:54:36.928+0000] {docker.py:73} INFO - The jars for the packages stored in: /home/jovyan/.ivy2/jars
[2024-12-23T18:54:36.933+0000] {docker.py:73} INFO - io.delta#delta-spark_2.12 added as a dependency
[2024-12-23T18:54:36.934+0000] {docker.py:73} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-2f3ba190-e536-441d-bcd5-308c98ec1d4e;1.0
[2024-12-23T18:54:36.935+0000] {docker.py:73} INFO - 	confs: [default]
[2024-12-23T18:54:39.147+0000] {docker.py:73} INFO - 	found io.delta#delta-spark_2.12;3.1.0 in central
[2024-12-23T18:54:39.682+0000] {docker.py:73} INFO - 	found io.delta#delta-storage;3.1.0 in central
[2024-12-23T18:54:42.819+0000] {docker.py:73} INFO - 	found org.antlr#antlr4-runtime;4.9.3 in central
[2024-12-23T18:54:43.097+0000] {docker.py:73} INFO - downloading https://repo1.maven.org/maven2/io/delta/delta-spark_2.12/3.1.0/delta-spark_2.12-3.1.0.jar ...
[2024-12-23T18:54:51.906+0000] {docker.py:73} INFO - 	[SUCCESSFUL ] io.delta#delta-spark_2.12;3.1.0!delta-spark_2.12.jar (9059ms)
[2024-12-23T18:54:52.187+0000] {docker.py:73} INFO - downloading https://repo1.maven.org/maven2/io/delta/delta-storage/3.1.0/delta-storage-3.1.0.jar ...
[2024-12-23T18:54:52.478+0000] {docker.py:73} INFO - 	[SUCCESSFUL ] io.delta#delta-storage;3.1.0!delta-storage.jar (561ms)
[2024-12-23T18:54:52.744+0000] {docker.py:73} INFO - downloading https://repo1.maven.org/maven2/org/antlr/antlr4-runtime/4.9.3/antlr4-runtime-4.9.3.jar ...
[2024-12-23T18:54:53.201+0000] {docker.py:73} INFO - 	[SUCCESSFUL ] org.antlr#antlr4-runtime;4.9.3!antlr4-runtime.jar (705ms)
[2024-12-23T18:54:53.203+0000] {docker.py:73} INFO - :: resolution report :: resolve 5904ms :: artifacts dl 10359ms
[2024-12-23T18:54:53.203+0000] {docker.py:73} INFO - 	:: modules in use:
[2024-12-23T18:54:53.205+0000] {docker.py:73} INFO - 	io.delta#delta-spark_2.12;3.1.0 from central in [default]
[2024-12-23T18:54:53.205+0000] {docker.py:73} INFO - 	io.delta#delta-storage;3.1.0 from central in [default]
[2024-12-23T18:54:53.206+0000] {docker.py:73} INFO - 	org.antlr#antlr4-runtime;4.9.3 from central in [default]
[2024-12-23T18:54:53.207+0000] {docker.py:73} INFO - 	---------------------------------------------------------------------
[2024-12-23T18:54:53.208+0000] {docker.py:73} INFO - 	|                  |            modules            ||   artifacts   |
[2024-12-23T18:54:53.208+0000] {docker.py:73} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2024-12-23T18:54:53.209+0000] {docker.py:73} INFO - 	---------------------------------------------------------------------
[2024-12-23T18:54:53.210+0000] {docker.py:73} INFO - 	|      default     |   3   |   3   |   3   |   0   ||   3   |   3   |
[2024-12-23T18:54:53.213+0000] {docker.py:73} INFO - 	---------------------------------------------------------------------
[2024-12-23T18:54:53.227+0000] {docker.py:73} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-2f3ba190-e536-441d-bcd5-308c98ec1d4e
[2024-12-23T18:54:53.228+0000] {docker.py:73} INFO - 	confs: [default]
[2024-12-23T18:54:53.275+0000] {docker.py:73} INFO - 	3 artifacts copied, 0 already retrieved (5727kB/47ms)
[2024-12-23T18:54:53.531+0000] {docker.py:73} INFO - 24/12/23 18:54:53 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-12-23T18:54:53.777+0000] {docker.py:73} INFO - Setting default log level to "WARN".
[2024-12-23T18:54:53.778+0000] {docker.py:73} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2024-12-23T18:54:54.920+0000] {docker.py:73} INFO - 24/12/23 18:54:54 WARN StandaloneSchedulerBackend: Dynamic allocation enabled without spark.executor.cores explicitly set, you may get more executors allocated than expected. It's recommended to set spark.executor.cores explicitly. Please check SPARK-30299 for more details.
[2024-12-23T18:54:55.388+0000] {docker.py:73} INFO - 24/12/23 18:54:55 WARN Utils: spark.executor.instances less than spark.dynamicAllocation.minExecutors is invalid, ignoring its setting, please update your configs.
[2024-12-23T18:54:58.391+0000] {docker.py:73} INFO - Executing:  23%|██▎       | 3/13 [01:14<04:06, 24.66s/cell]
[2024-12-23T18:54:59.495+0000] {docker.py:73} INFO - Executing:  38%|███▊      | 5/13 [01:15<01:28, 11.01s/cell]
[2024-12-23T18:55:02.258+0000] {docker.py:73} INFO - Executing:  38%|███▊      | 5/13 [01:17<02:04, 15.60s/cell]
[2024-12-23T18:55:02.303+0000] {docker.py:73} INFO - Traceback (most recent call last):
[2024-12-23T18:55:02.304+0000] {docker.py:73} INFO -   File "/opt/conda/bin/papermill", line 8, in <module>
[2024-12-23T18:55:02.305+0000] {docker.py:73} INFO -     sys.exit(papermill())
[2024-12-23T18:55:02.306+0000] {docker.py:73} INFO -              ^^^^^^^^^^^
[2024-12-23T18:55:02.306+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
[2024-12-23T18:55:02.307+0000] {docker.py:73} INFO -     return self.main(*args, **kwargs)
[2024-12-23T18:55:02.307+0000] {docker.py:73} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-23T18:55:02.308+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 1078, in main
[2024-12-23T18:55:02.308+0000] {docker.py:73} INFO -     rv = self.invoke(ctx)
[2024-12-23T18:55:02.308+0000] {docker.py:73} INFO -          ^^^^^^^^^^^^^^^^
[2024-12-23T18:55:02.308+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
[2024-12-23T18:55:02.309+0000] {docker.py:73} INFO -     return ctx.invoke(self.callback, **ctx.params)
[2024-12-23T18:55:02.310+0000] {docker.py:73} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-23T18:55:02.311+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 783, in invoke
[2024-12-23T18:55:02.311+0000] {docker.py:73} INFO -     return __callback(*args, **kwargs)
[2024-12-23T18:55:02.312+0000] {docker.py:73} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-23T18:55:02.312+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
[2024-12-23T18:55:02.312+0000] {docker.py:73} INFO -     return f(get_current_context(), *args, **kwargs)
[2024-12-23T18:55:02.312+0000] {docker.py:73} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-23T18:55:02.312+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/papermill/cli.py", line 235, in papermill
[2024-12-23T18:55:02.313+0000] {docker.py:73} INFO -     execute_notebook(
[2024-12-23T18:55:02.313+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/papermill/execute.py", line 131, in execute_notebook
[2024-12-23T18:55:02.313+0000] {docker.py:73} INFO -     raise_for_execution_errors(nb, output_path)
[2024-12-23T18:55:02.314+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/papermill/execute.py", line 251, in raise_for_execution_errors
[2024-12-23T18:55:02.314+0000] {docker.py:73} INFO -     raise error
[2024-12-23T18:55:02.315+0000] {docker.py:73} INFO - papermill.exceptions.PapermillExecutionError: 
[2024-12-23T18:55:02.315+0000] {docker.py:73} INFO - ---------------------------------------------------------------------------
[2024-12-23T18:55:02.315+0000] {docker.py:73} INFO - Exception encountered at "In [5]":
[2024-12-23T18:55:02.315+0000] {docker.py:73} INFO - ---------------------------------------------------------------------------
[2024-12-23T18:55:02.316+0000] {docker.py:73} INFO - FileNotFoundError                         Traceback (most recent call last)
[2024-12-23T18:55:02.316+0000] {docker.py:73} INFO - Cell In[5], line 2
[2024-12-23T18:55:02.316+0000] {docker.py:73} INFO -       1 # Read the Excel file (use Spark-Excel library)
[2024-12-23T18:55:02.316+0000] {docker.py:73} INFO - ----> 2 df = pd.read_excel(source_path, sheet_name = sheet_name)
[2024-12-23T18:55:02.321+0000] {docker.py:73} INFO -       3 df = spark.createDataFrame(df)
[2024-12-23T18:55:02.321+0000] {docker.py:73} INFO -       4 df= df.withColumn("Date", to_date(df["Date"],"yyyy-MM-dd"))
[2024-12-23T18:55:02.323+0000] {docker.py:73} INFO - 
[2024-12-23T18:55:02.324+0000] {docker.py:73} INFO - File /opt/conda/lib/python3.11/site-packages/pandas/io/excel/_base.py:478, in read_excel(io, sheet_name, header, names, index_col, usecols, dtype, engine, converters, true_values, false_values, skiprows, nrows, na_values, keep_default_na, na_filter, verbose, parse_dates, date_parser, date_format, thousands, decimal, comment, skipfooter, storage_options, dtype_backend)
[2024-12-23T18:55:02.325+0000] {docker.py:73} INFO -     476 if not isinstance(io, ExcelFile):
[2024-12-23T18:55:02.325+0000] {docker.py:73} INFO -     477     should_close = True
[2024-12-23T18:55:02.326+0000] {docker.py:73} INFO - --> 478     io = ExcelFile(io, storage_options=storage_options, engine=engine)
[2024-12-23T18:55:02.327+0000] {docker.py:73} INFO -     479 elif engine and engine != io.engine:
[2024-12-23T18:55:02.327+0000] {docker.py:73} INFO -     480     raise ValueError(
[2024-12-23T18:55:02.327+0000] {docker.py:73} INFO -     481         "Engine should not be specified when passing "
[2024-12-23T18:55:02.328+0000] {docker.py:73} INFO -     482         "an ExcelFile - ExcelFile already has the engine set"
[2024-12-23T18:55:02.328+0000] {docker.py:73} INFO -     483     )
[2024-12-23T18:55:02.329+0000] {docker.py:73} INFO - 
[2024-12-23T18:55:02.329+0000] {docker.py:73} INFO - File /opt/conda/lib/python3.11/site-packages/pandas/io/excel/_base.py:1496, in ExcelFile.__init__(self, path_or_buffer, engine, storage_options)
[2024-12-23T18:55:02.330+0000] {docker.py:73} INFO -    1494     ext = "xls"
[2024-12-23T18:55:02.330+0000] {docker.py:73} INFO -    1495 else:
[2024-12-23T18:55:02.330+0000] {docker.py:73} INFO - -> 1496     ext = inspect_excel_format(
[2024-12-23T18:55:02.330+0000] {docker.py:73} INFO -    1497         content_or_path=path_or_buffer, storage_options=storage_options
[2024-12-23T18:55:02.330+0000] {docker.py:73} INFO -    1498     )
[2024-12-23T18:55:02.330+0000] {docker.py:73} INFO -    1499     if ext is None:
[2024-12-23T18:55:02.331+0000] {docker.py:73} INFO -    1500         raise ValueError(
[2024-12-23T18:55:02.331+0000] {docker.py:73} INFO -    1501             "Excel file format cannot be determined, you must specify "
[2024-12-23T18:55:02.331+0000] {docker.py:73} INFO -    1502             "an engine manually."
[2024-12-23T18:55:02.331+0000] {docker.py:73} INFO -    1503         )
[2024-12-23T18:55:02.332+0000] {docker.py:73} INFO - 
[2024-12-23T18:55:02.332+0000] {docker.py:73} INFO - File /opt/conda/lib/python3.11/site-packages/pandas/io/excel/_base.py:1371, in inspect_excel_format(content_or_path, storage_options)
[2024-12-23T18:55:02.332+0000] {docker.py:73} INFO -    1368 if isinstance(content_or_path, bytes):
[2024-12-23T18:55:02.333+0000] {docker.py:73} INFO -    1369     content_or_path = BytesIO(content_or_path)
[2024-12-23T18:55:02.334+0000] {docker.py:73} INFO - -> 1371 with get_handle(
[2024-12-23T18:55:02.334+0000] {docker.py:73} INFO -    1372     content_or_path, "rb", storage_options=storage_options, is_text=False
[2024-12-23T18:55:02.335+0000] {docker.py:73} INFO -    1373 ) as handle:
[2024-12-23T18:55:02.336+0000] {docker.py:73} INFO -    1374     stream = handle.handle
[2024-12-23T18:55:02.338+0000] {docker.py:73} INFO -    1375     stream.seek(0)
[2024-12-23T18:55:02.341+0000] {docker.py:73} INFO - 
[2024-12-23T18:55:02.343+0000] {docker.py:73} INFO - File /opt/conda/lib/python3.11/site-packages/pandas/io/common.py:868, in get_handle(path_or_buf, mode, encoding, compression, memory_map, is_text, errors, storage_options)
[2024-12-23T18:55:02.345+0000] {docker.py:73} INFO -     859         handle = open(
[2024-12-23T18:55:02.348+0000] {docker.py:73} INFO -     860             handle,
[2024-12-23T18:55:02.350+0000] {docker.py:73} INFO -     861             ioargs.mode,
[2024-12-23T18:55:02.351+0000] {docker.py:73} INFO -    (...)
[2024-12-23T18:55:02.352+0000] {docker.py:73} INFO -     864             newline="",
[2024-12-23T18:55:02.353+0000] {docker.py:73} INFO -     865         )
[2024-12-23T18:55:02.353+0000] {docker.py:73} INFO -     866     else:
[2024-12-23T18:55:02.355+0000] {docker.py:73} INFO -     867         # Binary mode
[2024-12-23T18:55:02.356+0000] {docker.py:73} INFO - --> 868         handle = open(handle, ioargs.mode)
[2024-12-23T18:55:02.357+0000] {docker.py:73} INFO -     869     handles.append(handle)
[2024-12-23T18:55:02.357+0000] {docker.py:73} INFO -     871 # Convert BytesIO or file objects passed with an encoding
[2024-12-23T18:55:02.359+0000] {docker.py:73} INFO - 
[2024-12-23T18:55:02.359+0000] {docker.py:73} INFO - FileNotFoundError: [Errno 2] No such file or directory: '/data/Project_Files/Template.xlsm'
[2024-12-23T18:55:03.313+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 519, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 396, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 453, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2024-12-23T18:55:03.353+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dag_Category_NTBK, task_id=NB_Notebook_job, run_id=manual__2024-12-23T18:53:18.419471+00:00, execution_date=20241223T185318, start_date=20241223T185324, end_date=20241223T185503
[2024-12-23T18:55:03.432+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-23T18:55:03.434+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 268 for task NB_Notebook_job (Docker container failed: {'StatusCode': 1}; 1791)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 519, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 396, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 453, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2024-12-23T18:55:03.481+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-23T18:55:03.549+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-23T18:55:03.552+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
