[2024-12-23T11:07:47.735+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-23T11:07:47.745+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_Calendar_NTBK.NB_Notebook_job manual__2024-12-23T11:07:44.776543+00:00 [queued]>
[2024-12-23T11:07:47.750+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_Calendar_NTBK.NB_Notebook_job manual__2024-12-23T11:07:44.776543+00:00 [queued]>
[2024-12-23T11:07:47.750+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-23T11:07:47.757+0000] {taskinstance.py:2889} INFO - Executing <Task(DockerOperator): NB_Notebook_job> on 2024-12-23 11:07:44.776543+00:00
[2024-12-23T11:07:47.762+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1320) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-23T11:07:47.764+0000] {standard_task_runner.py:72} INFO - Started process 1321 to run task
[2024-12-23T11:07:47.764+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_Calendar_NTBK', 'NB_Notebook_job', 'manual__2024-12-23T11:07:44.776543+00:00', '--job-id', '212', '--raw', '--subdir', 'DAGS_FOLDER/A_dag_test.py', '--cfg-path', '/tmp/tmpgtn_jodq']
[2024-12-23T11:07:47.765+0000] {standard_task_runner.py:105} INFO - Job 212: Subtask NB_Notebook_job
[2024-12-23T11:07:47.808+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_Calendar_NTBK.NB_Notebook_job manual__2024-12-23T11:07:44.776543+00:00 [running]> on host 85f5ad808200
[2024-12-23T11:07:47.860+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_Calendar_NTBK' AIRFLOW_CTX_TASK_ID='NB_Notebook_job' AIRFLOW_CTX_EXECUTION_DATE='2024-12-23T11:07:44.776543+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-23T11:07:44.776543+00:00'
[2024-12-23T11:07:47.861+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-23T11:07:47.945+0000] {docker.py:379} INFO - Starting docker container from image spark-cluster:version-1.0.0
[2024-12-23T11:07:50.185+0000] {docker.py:73} INFO - Input Notebook:  /home/jovyan/Notebooks/NB_Calendar.ipynb
[2024-12-23T11:07:50.188+0000] {docker.py:73} INFO - Output Notebook: /home/jovyan/Notebooks/output-NB_Calendar.ipynb
[2024-12-23T11:07:50.233+0000] {docker.py:73} INFO - Executing:   0%|          | 0/14 [00:00<?, ?cell/s]
[2024-12-23T11:07:51.478+0000] {docker.py:73} INFO - Executing notebook with kernel: python3
[2024-12-23T11:07:52.190+0000] {docker.py:73} INFO - Executing:   7%|▋         | 1/14 [00:01<00:25,  1.95s/cell]
[2024-12-23T11:07:54.479+0000] {docker.py:73} INFO - :: loading settings :: url = jar:file:/usr/local/spark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2024-12-23T11:07:54.588+0000] {docker.py:73} INFO - Ivy Default Cache set to: /home/jovyan/.ivy2/cache
[2024-12-23T11:07:54.589+0000] {docker.py:73} INFO - The jars for the packages stored in: /home/jovyan/.ivy2/jars
[2024-12-23T11:07:54.594+0000] {docker.py:73} INFO - io.delta#delta-spark_2.12 added as a dependency
[2024-12-23T11:07:54.597+0000] {docker.py:73} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-0f676feb-f8f8-4d21-a217-a730fb11d93e;1.0
[2024-12-23T11:07:54.602+0000] {docker.py:73} INFO - 	confs: [default]
[2024-12-23T11:08:02.858+0000] {docker.py:73} INFO - You probably access the destination server through a proxy server that is not well configured.
[2024-12-23T11:08:02.869+0000] {docker.py:73} INFO - You probably access the destination server through a proxy server that is not well configured.
[2024-12-23T11:08:10.895+0000] {docker.py:73} INFO - You probably access the destination server through a proxy server that is not well configured.
[2024-12-23T11:08:10.917+0000] {docker.py:73} INFO - You probably access the destination server through a proxy server that is not well configured.
[2024-12-23T11:08:10.968+0000] {docker.py:73} INFO - :: resolution report :: resolve 16374ms :: artifacts dl 0ms
[2024-12-23T11:08:10.969+0000] {docker.py:73} INFO - 	:: modules in use:
[2024-12-23T11:08:10.969+0000] {docker.py:73} INFO - 	---------------------------------------------------------------------
[2024-12-23T11:08:10.969+0000] {docker.py:73} INFO - 	|                  |            modules            ||   artifacts   |
[2024-12-23T11:08:10.969+0000] {docker.py:73} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2024-12-23T11:08:10.970+0000] {docker.py:73} INFO - 	---------------------------------------------------------------------
[2024-12-23T11:08:10.970+0000] {docker.py:73} INFO - 	|      default     |   1   |   0   |   0   |   0   ||   0   |   0   |
[2024-12-23T11:08:10.970+0000] {docker.py:73} INFO - 	---------------------------------------------------------------------
[2024-12-23T11:08:10.972+0000] {docker.py:73} INFO - 
[2024-12-23T11:08:10.972+0000] {docker.py:73} INFO - :: problems summary ::
[2024-12-23T11:08:10.972+0000] {docker.py:73} INFO - :::: WARNINGS
[2024-12-23T11:08:10.972+0000] {docker.py:73} INFO - 	Host repo1.maven.org not found. url=https://repo1.maven.org/maven2/io/delta/delta-spark_2.12/3.1.0/delta-spark_2.12-3.1.0.pom
[2024-12-23T11:08:10.973+0000] {docker.py:73} INFO - 
[2024-12-23T11:08:10.973+0000] {docker.py:73} INFO - 	Host repo1.maven.org not found. url=https://repo1.maven.org/maven2/io/delta/delta-spark_2.12/3.1.0/delta-spark_2.12-3.1.0.jar
[2024-12-23T11:08:10.973+0000] {docker.py:73} INFO - 
[2024-12-23T11:08:10.973+0000] {docker.py:73} INFO - 	Host repos.spark-packages.org not found. url=https://repos.spark-packages.org/io/delta/delta-spark_2.12/3.1.0/delta-spark_2.12-3.1.0.pom
[2024-12-23T11:08:10.974+0000] {docker.py:73} INFO - 
[2024-12-23T11:08:10.974+0000] {docker.py:73} INFO - 	Host repos.spark-packages.org not found. url=https://repos.spark-packages.org/io/delta/delta-spark_2.12/3.1.0/delta-spark_2.12-3.1.0.jar
[2024-12-23T11:08:10.974+0000] {docker.py:73} INFO - 
[2024-12-23T11:08:10.974+0000] {docker.py:73} INFO - 		module not found: io.delta#delta-spark_2.12;3.1.0
[2024-12-23T11:08:10.974+0000] {docker.py:73} INFO - 
[2024-12-23T11:08:10.975+0000] {docker.py:73} INFO - 	==== local-m2-cache: tried
[2024-12-23T11:08:10.975+0000] {docker.py:73} INFO - 
[2024-12-23T11:08:10.975+0000] {docker.py:73} INFO - 	  file:/home/jovyan/.m2/repository/io/delta/delta-spark_2.12/3.1.0/delta-spark_2.12-3.1.0.pom
[2024-12-23T11:08:10.975+0000] {docker.py:73} INFO - 
[2024-12-23T11:08:10.975+0000] {docker.py:73} INFO - 	  -- artifact io.delta#delta-spark_2.12;3.1.0!delta-spark_2.12.jar:
[2024-12-23T11:08:10.975+0000] {docker.py:73} INFO - 
[2024-12-23T11:08:10.975+0000] {docker.py:73} INFO - 	  file:/home/jovyan/.m2/repository/io/delta/delta-spark_2.12/3.1.0/delta-spark_2.12-3.1.0.jar
[2024-12-23T11:08:10.975+0000] {docker.py:73} INFO - 
[2024-12-23T11:08:10.976+0000] {docker.py:73} INFO - 	==== local-ivy-cache: tried
[2024-12-23T11:08:10.976+0000] {docker.py:73} INFO - 
[2024-12-23T11:08:10.976+0000] {docker.py:73} INFO - 	  /home/jovyan/.ivy2/local/io.delta/delta-spark_2.12/3.1.0/ivys/ivy.xml
[2024-12-23T11:08:10.976+0000] {docker.py:73} INFO - 
[2024-12-23T11:08:10.976+0000] {docker.py:73} INFO - 	  -- artifact io.delta#delta-spark_2.12;3.1.0!delta-spark_2.12.jar:
[2024-12-23T11:08:10.976+0000] {docker.py:73} INFO - 	  /home/jovyan/.ivy2/local/io.delta/delta-spark_2.12/3.1.0/jars/delta-spark_2.12.jar
[2024-12-23T11:08:10.976+0000] {docker.py:73} INFO - 
[2024-12-23T11:08:10.976+0000] {docker.py:73} INFO - 	==== central: tried
[2024-12-23T11:08:10.977+0000] {docker.py:73} INFO - 	  https://repo1.maven.org/maven2/io/delta/delta-spark_2.12/3.1.0/delta-spark_2.12-3.1.0.pom
[2024-12-23T11:08:10.977+0000] {docker.py:73} INFO - 	  -- artifact io.delta#delta-spark_2.12;3.1.0!delta-spark_2.12.jar:
[2024-12-23T11:08:10.977+0000] {docker.py:73} INFO - 
[2024-12-23T11:08:10.977+0000] {docker.py:73} INFO - 	  https://repo1.maven.org/maven2/io/delta/delta-spark_2.12/3.1.0/delta-spark_2.12-3.1.0.jar
[2024-12-23T11:08:10.978+0000] {docker.py:73} INFO - 
[2024-12-23T11:08:10.978+0000] {docker.py:73} INFO - 	==== spark-packages: tried
[2024-12-23T11:08:10.978+0000] {docker.py:73} INFO - 
[2024-12-23T11:08:10.978+0000] {docker.py:73} INFO - 	  https://repos.spark-packages.org/io/delta/delta-spark_2.12/3.1.0/delta-spark_2.12-3.1.0.pom
[2024-12-23T11:08:10.978+0000] {docker.py:73} INFO - 	  -- artifact io.delta#delta-spark_2.12;3.1.0!delta-spark_2.12.jar:
[2024-12-23T11:08:10.979+0000] {docker.py:73} INFO - 
[2024-12-23T11:08:10.979+0000] {docker.py:73} INFO - 	  https://repos.spark-packages.org/io/delta/delta-spark_2.12/3.1.0/delta-spark_2.12-3.1.0.jar
[2024-12-23T11:08:10.979+0000] {docker.py:73} INFO - 
[2024-12-23T11:08:10.979+0000] {docker.py:73} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2024-12-23T11:08:10.979+0000] {docker.py:73} INFO - 
[2024-12-23T11:08:10.979+0000] {docker.py:73} INFO - 		::          UNRESOLVED DEPENDENCIES         ::
[2024-12-23T11:08:10.979+0000] {docker.py:73} INFO - 
[2024-12-23T11:08:10.979+0000] {docker.py:73} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2024-12-23T11:08:10.980+0000] {docker.py:73} INFO - 
[2024-12-23T11:08:10.980+0000] {docker.py:73} INFO - 		:: io.delta#delta-spark_2.12;3.1.0: not found
[2024-12-23T11:08:10.980+0000] {docker.py:73} INFO - 
[2024-12-23T11:08:10.980+0000] {docker.py:73} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2024-12-23T11:08:10.980+0000] {docker.py:73} INFO - 
[2024-12-23T11:08:10.980+0000] {docker.py:73} INFO - 
[2024-12-23T11:08:10.981+0000] {docker.py:73} INFO - 
[2024-12-23T11:08:10.981+0000] {docker.py:73} INFO - :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
[2024-12-23T11:08:10.981+0000] {docker.py:73} INFO - Exception in thread "main"
[2024-12-23T11:08:10.981+0000] {docker.py:73} INFO - java.lang.RuntimeException: [unresolved dependency: io.delta#delta-spark_2.12;3.1.0: not found]
[2024-12-23T11:08:10.982+0000] {docker.py:73} INFO - 	at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1537)
[2024-12-23T11:08:10.982+0000] {docker.py:73} INFO - 	at org.apache.spark.util.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:185)
[2024-12-23T11:08:10.982+0000] {docker.py:73} INFO - 	at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:334)
[2024-12-23T11:08:10.982+0000] {docker.py:73} INFO - 	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:964)
[2024-12-23T11:08:10.982+0000] {docker.py:73} INFO - 	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:194)
[2024-12-23T11:08:10.982+0000] {docker.py:73} INFO - 	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:217)
[2024-12-23T11:08:10.982+0000] {docker.py:73} INFO - 	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:91)
[2024-12-23T11:08:10.983+0000] {docker.py:73} INFO - 	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1120)
[2024-12-23T11:08:10.983+0000] {docker.py:73} INFO - 	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1129)
[2024-12-23T11:08:10.983+0000] {docker.py:73} INFO - 	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2024-12-23T11:08:11.405+0000] {docker.py:73} INFO - Executing:  21%|██▏       | 3/14 [00:21<01:23,  7.62s/cell]
[2024-12-23T11:08:11.736+0000] {docker.py:73} INFO - Executing:  21%|██▏       | 3/14 [00:21<01:18,  7.17s/cell]
[2024-12-23T11:08:11.743+0000] {docker.py:73} INFO - Traceback (most recent call last):
[2024-12-23T11:08:11.743+0000] {docker.py:73} INFO -   File "/opt/conda/bin/papermill", line 8, in <module>
[2024-12-23T11:08:11.743+0000] {docker.py:73} INFO -     sys.exit(papermill())
[2024-12-23T11:08:11.744+0000] {docker.py:73} INFO -              ^^^^^^^^^^^
[2024-12-23T11:08:11.744+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
[2024-12-23T11:08:11.744+0000] {docker.py:73} INFO -     return self.main(*args, **kwargs)
[2024-12-23T11:08:11.745+0000] {docker.py:73} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-23T11:08:11.745+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 1078, in main
[2024-12-23T11:08:11.746+0000] {docker.py:73} INFO -     rv = self.invoke(ctx)
[2024-12-23T11:08:11.746+0000] {docker.py:73} INFO -          ^^^^^^^^^^^^^^^^
[2024-12-23T11:08:11.746+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
[2024-12-23T11:08:11.746+0000] {docker.py:73} INFO -     return ctx.invoke(self.callback, **ctx.params)
[2024-12-23T11:08:11.747+0000] {docker.py:73} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-23T11:08:11.748+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 783, in invoke
[2024-12-23T11:08:11.748+0000] {docker.py:73} INFO -     return __callback(*args, **kwargs)
[2024-12-23T11:08:11.748+0000] {docker.py:73} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-23T11:08:11.749+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
[2024-12-23T11:08:11.749+0000] {docker.py:73} INFO -     return f(get_current_context(), *args, **kwargs)
[2024-12-23T11:08:11.749+0000] {docker.py:73} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-23T11:08:11.749+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/papermill/cli.py", line 235, in papermill
[2024-12-23T11:08:11.749+0000] {docker.py:73} INFO -     execute_notebook(
[2024-12-23T11:08:11.750+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/papermill/execute.py", line 131, in execute_notebook
[2024-12-23T11:08:11.750+0000] {docker.py:73} INFO -     raise_for_execution_errors(nb, output_path)
[2024-12-23T11:08:11.750+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/papermill/execute.py", line 251, in raise_for_execution_errors
[2024-12-23T11:08:11.750+0000] {docker.py:73} INFO -     raise error
[2024-12-23T11:08:11.751+0000] {docker.py:73} INFO - papermill.exceptions.PapermillExecutionError: 
[2024-12-23T11:08:11.751+0000] {docker.py:73} INFO - ---------------------------------------------------------------------------
[2024-12-23T11:08:11.751+0000] {docker.py:73} INFO - Exception encountered at "In [3]":
[2024-12-23T11:08:11.752+0000] {docker.py:73} INFO - ---------------------------------------------------------------------------
[2024-12-23T11:08:11.752+0000] {docker.py:73} INFO - PySparkRuntimeError                       Traceback (most recent call last)
[2024-12-23T11:08:11.752+0000] {docker.py:73} INFO - Cell In[3], line 2
[2024-12-23T11:08:11.752+0000] {docker.py:73} INFO -       1 # Configure Spark with Delta Lake (if needed)
[2024-12-23T11:08:11.753+0000] {docker.py:73} INFO - ----> 2 spark = configure_spark_with_delta_pip(builder).getOrCreate()
[2024-12-23T11:08:11.753+0000] {docker.py:73} INFO -       4 driver_version = sys.version_info
[2024-12-23T11:08:11.753+0000] {docker.py:73} INFO -       5 worker_version = spark.sparkContext.pythonExec
[2024-12-23T11:08:11.753+0000] {docker.py:73} INFO - 
[2024-12-23T11:08:11.754+0000] {docker.py:73} INFO - File /opt/conda/lib/python3.11/site-packages/pyspark/sql/session.py:497, in SparkSession.Builder.getOrCreate(self)
[2024-12-23T11:08:11.754+0000] {docker.py:73} INFO -     495     sparkConf.set(key, value)
[2024-12-23T11:08:11.754+0000] {docker.py:73} INFO -     496 # This SparkContext may be an existing one.
[2024-12-23T11:08:11.754+0000] {docker.py:73} INFO - --> 497 sc = SparkContext.getOrCreate(sparkConf)
[2024-12-23T11:08:11.754+0000] {docker.py:73} INFO -     498 # Do not update `SparkConf` for existing `SparkContext`, as it's shared
[2024-12-23T11:08:11.754+0000] {docker.py:73} INFO -     499 # by all sessions.
[2024-12-23T11:08:11.755+0000] {docker.py:73} INFO -     500 session = SparkSession(sc, options=self._options)
[2024-12-23T11:08:11.755+0000] {docker.py:73} INFO - 
[2024-12-23T11:08:11.755+0000] {docker.py:73} INFO - File /opt/conda/lib/python3.11/site-packages/pyspark/context.py:515, in SparkContext.getOrCreate(cls, conf)
[2024-12-23T11:08:11.755+0000] {docker.py:73} INFO -     513 with SparkContext._lock:
[2024-12-23T11:08:11.755+0000] {docker.py:73} INFO -     514     if SparkContext._active_spark_context is None:
[2024-12-23T11:08:11.756+0000] {docker.py:73} INFO - --> 515         SparkContext(conf=conf or SparkConf())
[2024-12-23T11:08:11.756+0000] {docker.py:73} INFO -     516     assert SparkContext._active_spark_context is not None
[2024-12-23T11:08:11.756+0000] {docker.py:73} INFO -     517     return SparkContext._active_spark_context
[2024-12-23T11:08:11.756+0000] {docker.py:73} INFO - 
[2024-12-23T11:08:11.756+0000] {docker.py:73} INFO - File /opt/conda/lib/python3.11/site-packages/pyspark/context.py:201, in SparkContext.__init__(self, master, appName, sparkHome, pyFiles, environment, batchSize, serializer, conf, gateway, jsc, profiler_cls, udf_profiler_cls, memory_profiler_cls)
[2024-12-23T11:08:11.756+0000] {docker.py:73} INFO -     195 if gateway is not None and gateway.gateway_parameters.auth_token is None:
[2024-12-23T11:08:11.757+0000] {docker.py:73} INFO -     196     raise ValueError(
[2024-12-23T11:08:11.757+0000] {docker.py:73} INFO -     197         "You are trying to pass an insecure Py4j gateway to Spark. This"
[2024-12-23T11:08:11.757+0000] {docker.py:73} INFO -     198         " is not allowed as it is a security risk."
[2024-12-23T11:08:11.757+0000] {docker.py:73} INFO -     199     )
[2024-12-23T11:08:11.757+0000] {docker.py:73} INFO - --> 201 SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
[2024-12-23T11:08:11.757+0000] {docker.py:73} INFO -     202 try:
[2024-12-23T11:08:11.757+0000] {docker.py:73} INFO -     203     self._do_init(
[2024-12-23T11:08:11.758+0000] {docker.py:73} INFO -     204         master,
[2024-12-23T11:08:11.758+0000] {docker.py:73} INFO -     205         appName,
[2024-12-23T11:08:11.758+0000] {docker.py:73} INFO -    (...)
[2024-12-23T11:08:11.758+0000] {docker.py:73} INFO -     215         memory_profiler_cls,
[2024-12-23T11:08:11.758+0000] {docker.py:73} INFO -     216     )
[2024-12-23T11:08:11.758+0000] {docker.py:73} INFO - 
[2024-12-23T11:08:11.759+0000] {docker.py:73} INFO - File /opt/conda/lib/python3.11/site-packages/pyspark/context.py:436, in SparkContext._ensure_initialized(cls, instance, gateway, conf)
[2024-12-23T11:08:11.759+0000] {docker.py:73} INFO -     434 with SparkContext._lock:
[2024-12-23T11:08:11.759+0000] {docker.py:73} INFO -     435     if not SparkContext._gateway:
[2024-12-23T11:08:11.759+0000] {docker.py:73} INFO - --> 436         SparkContext._gateway = gateway or launch_gateway(conf)
[2024-12-23T11:08:11.759+0000] {docker.py:73} INFO -     437         SparkContext._jvm = SparkContext._gateway.jvm
[2024-12-23T11:08:11.759+0000] {docker.py:73} INFO -     439     if instance:
[2024-12-23T11:08:11.759+0000] {docker.py:73} INFO - 
[2024-12-23T11:08:11.759+0000] {docker.py:73} INFO - File /opt/conda/lib/python3.11/site-packages/pyspark/java_gateway.py:107, in launch_gateway(conf, popen_kwargs)
[2024-12-23T11:08:11.760+0000] {docker.py:73} INFO -     104     time.sleep(0.1)
[2024-12-23T11:08:11.760+0000] {docker.py:73} INFO -     106 if not os.path.isfile(conn_info_file):
[2024-12-23T11:08:11.760+0000] {docker.py:73} INFO - --> 107     raise PySparkRuntimeError(
[2024-12-23T11:08:11.760+0000] {docker.py:73} INFO -     108         error_class="JAVA_GATEWAY_EXITED",
[2024-12-23T11:08:11.760+0000] {docker.py:73} INFO -     109         message_parameters={},
[2024-12-23T11:08:11.760+0000] {docker.py:73} INFO -     110     )
[2024-12-23T11:08:11.761+0000] {docker.py:73} INFO -     112 with open(conn_info_file, "rb") as info:
[2024-12-23T11:08:11.761+0000] {docker.py:73} INFO -     113     gateway_port = read_int(info)
[2024-12-23T11:08:11.761+0000] {docker.py:73} INFO - 
[2024-12-23T11:08:11.761+0000] {docker.py:73} INFO - PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-12-23T11:08:12.241+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 519, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 396, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 453, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2024-12-23T11:08:12.259+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dag_Calendar_NTBK, task_id=NB_Notebook_job, run_id=manual__2024-12-23T11:07:44.776543+00:00, execution_date=20241223T110744, start_date=20241223T110747, end_date=20241223T110812
[2024-12-23T11:08:12.311+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-23T11:08:12.321+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 212 for task NB_Notebook_job (Docker container failed: {'StatusCode': 1}; 1321)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 519, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 396, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 453, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2024-12-23T11:08:12.381+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-23T11:08:12.422+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-23T11:08:12.429+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
